Galeb: com.globo.galeb.metrics.CounterConsoleOut Class Reference
com.globo.galeb.metrics.CounterConsoleOut Class Reference
Public Member Functions
void httpCode (String key, Integer code)
void httpCode (String serverHost, String backendId, Integer code)
void incrHttpCode (String key, Integer code)
void incrHttpCode (String key, Integer code, double sample)
void decrHttpCode (String key, Integer code)
void decrHttpCode (String key, Integer code, double sample)
void requestTime (String key, Long initialRequestTime)
void requestTime (String serverHost, String backendId, Long initialRequestTime)
void sendActiveSessions (String key, Long initialRequestTime)
void sendActiveSessions (String serverHost, String backendId, Long initialRequestTime)
Detailed Description
Class CounterConsoleOut: metrics console output
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Member Function Documentation
void com.globo.galeb.metrics.CounterConsoleOut.decrHttpCode (String key, Integer code)
Decrement http code count.
Parameters
key the key
code the code
Implements com.globo.galeb.metrics.ICounter.
void com.globo.galeb.metrics.CounterConsoleOut.decrHttpCode (String key, Integer code, double sample)
Decrement http code count.
Parameters
key the key
code the code
sample the sample
Implements com.globo.galeb.metrics.ICounter.
void com.globo.galeb.metrics.CounterConsoleOut.httpCode (String key, Integer code)
http code count.
Parameters
key the key
code the code
Implements com.globo.galeb.metrics.ICounter.
Referenced by com.globo.galeb.metrics.CounterConsoleOut.httpCode().
void com.globo.galeb.metrics.CounterConsoleOut.httpCode (String virtualhostId, String backendId, Integer code)
http code count.
Parameters
virtualhostId the virtualhost id
backendId the backend id
code the code
Implements com.globo.galeb.metrics.ICounter.
References com.globo.galeb.metrics.CounterConsoleOut.httpCode().
void com.globo.galeb.metrics.CounterConsoleOut.incrHttpCode (String key, Integer code)
Increment http code count.
Parameters
key the key
code the code
Implements com.globo.galeb.metrics.ICounter.
void com.globo.galeb.metrics.CounterConsoleOut.incrHttpCode (String key, Integer code, double sample)
Increment http code count.
Parameters
key the key
code the code
sample the sample
Implements com.globo.galeb.metrics.ICounter.
void com.globo.galeb.metrics.CounterConsoleOut.requestTime (String key, Long initialRequestTime)
Request time count.
Parameters
key the key
initialRequestTime the initial request time
Implements com.globo.galeb.metrics.ICounter.
Referenced by com.globo.galeb.metrics.CounterConsoleOut.requestTime().
void com.globo.galeb.metrics.CounterConsoleOut.requestTime (String virtualhostId, String backendId, Long initialRequestTime)
Request time count.
Parameters
virtualhostId the virtualhost id
backendId the backend id
initialRequestTime the initial request time
Implements com.globo.galeb.metrics.ICounter.
References com.globo.galeb.metrics.CounterConsoleOut.requestTime().
void com.globo.galeb.metrics.CounterConsoleOut.sendActiveSessions (String key, Long initialRequestTime)
Send active sessions.
Parameters
key the key
initialRequestTime the initial request time
Implements com.globo.galeb.metrics.ICounter.
Referenced by com.globo.galeb.metrics.CounterConsoleOut.sendActiveSessions().
void com.globo.galeb.metrics.CounterConsoleOut.sendActiveSessions (String virtualhostId, String backendId, Long initialRequestTime)
Send active sessions.
Parameters
virtualhostId the virtualhost id
backendId the backend id
initialRequestTime the initial request time
Implements com.globo.galeb.metrics.ICounter.
References com.globo.galeb.metrics.CounterConsoleOut.sendActiveSessions().
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/metrics/CounterConsoleOut.java