Galeb: com.globo.galeb.handlers.RouterResponseHandler Class Reference
com.globo.galeb.handlers.RouterResponseHandler Class Reference
Public Member Functions
void handle (final HttpClientResponse cResponse) throws RuntimeException
RouterResponseHandler setHeaderHost (String headerHost)
Long getInitialRequestTime ()
RouterResponseHandler setInitialRequestTime (Long initialRequestTime)
boolean isConnectionKeepalive ()
RouterResponseHandler setConnectionKeepalive (boolean connectionKeepalive)
RouterResponseHandler (final IScheduler scheduler, final IQueueService queueService, final Logger log, final HttpServerResponse httpServerResponse, final ServerResponse sResponse, final Backend backend, final RemoteUser remoteUser)
RouterResponseHandler (final IScheduler scheduler, final IQueueService queueService, final Logger log, final HttpServerResponse httpServerResponse, final ServerResponse sResponse, final Backend backend, final RemoteUser remoteUser, final ICounter counter)
Detailed Description
Class RouterResponseHandler.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Constructor & Destructor Documentation
com.globo.galeb.handlers.RouterResponseHandler.RouterResponseHandler (final IScheduler scheduler, final IQueueService queueService, final Logger log, final HttpServerResponse httpServerResponse, final ServerResponse sResponse, final Backend backend, final RemoteUser remoteUser)
Instantiates a new router response handler.
Parameters
vertx the vertx
log the log
requestTimeoutTimer the request timeout timer
httpServerResponse the http server response
sResponse the s response
backend the backend
remoteUser the remote user
com.globo.galeb.handlers.RouterResponseHandler.RouterResponseHandler (final IScheduler scheduler, final IQueueService queueService, final Logger log, final HttpServerResponse httpServerResponse, final ServerResponse sResponse, final Backend backend, final RemoteUser remoteUser, final ICounter counter)
Instantiates a new router response handler.
Parameters
vertx the vertx
log the log
requestTimeoutTimer the request timeout timer
httpServerResponse the http server response
sResponse the s response
backend the backend
remoteUser the remote user
counter the counter
Member Function Documentation
Long com.globo.galeb.handlers.RouterResponseHandler.getInitialRequestTime ()
Gets the initial request time.
Returns
the initial request time
void com.globo.galeb.handlers.RouterResponseHandler.handle (final HttpClientResponse cResponse) throws RuntimeException
References com.globo.galeb.streams.Pump.bytesPumped(), com.globo.galeb.scheduler.IScheduler.cancel(), com.globo.galeb.core.Backend.close(), com.globo.galeb.core.ServerResponse.closeResponse(), com.globo.galeb.core.ServerResponse.endResponse(), com.globo.galeb.core.bus.IQueueService.publishBackendFail(), com.globo.galeb.core.Backend.removeSession(), com.globo.galeb.metrics.ICounter.requestTime(), com.globo.galeb.core.ServerResponse.setBackendId(), com.globo.galeb.core.ServerResponse.setHeaderHost(), com.globo.galeb.core.ServerResponse.setHeaders(), com.globo.galeb.core.ServerResponse.setStatusCode(), com.globo.galeb.core.ServerResponse.showErrorAndClose(), com.globo.galeb.streams.Pump.start(), and com.globo.galeb.core.Backend.toString().
boolean com.globo.galeb.handlers.RouterResponseHandler.isConnectionKeepalive ()
Checks if is connection keepalive.
Returns
true, if is connection keepalive
RouterResponseHandler com.globo.galeb.handlers.RouterResponseHandler.setConnectionKeepalive (boolean connectionKeepalive)
Sets the connection keepalive.
Parameters
connectionKeepalive the connection keepalive
Returns
the router response handler
RouterResponseHandler com.globo.galeb.handlers.RouterResponseHandler.setHeaderHost (String headerHost)
Sets the header host.
Parameters
headerHost the header host
Returns
the router response handler
Referenced by com.globo.galeb.handlers.RouterRequestHandler.handle().
RouterResponseHandler com.globo.galeb.handlers.RouterResponseHandler.setInitialRequestTime (Long initialRequestTime)
Sets the initial request time.
Parameters
initialRequestTime the initial request time
Returns
the router response handler
Referenced by com.globo.galeb.handlers.RouterRequestHandler.handle().
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/handlers/RouterResponseHandler.java