Galeb: com.globo.galeb.core.bus.MessageToMap< T > Class Reference
com.globo.galeb.core.bus.MessageToMap< T > Class Reference abstract
Public Member Functions
MessageToMap< T > setVerticleId (String id)
MessageToMap< T > setLogger (final Logger log)
MessageToMap< T > setMessageBus (final MessageBus messageBus)
MessageToMap< T > setMap (final Map< String, T > map)
MessageToMap< T > setVertx (final Vertx vertx)
boolean add ()
boolean del ()
boolean reset ()
boolean change ()
MessageToMap< T > staticConf (String jsonConf)
Protected Attributes
String uriBase = ""
JsonObject entity = new JsonObject()
String entityId = ""
String parentId = ""
Map< String, T > map = new HashMap<>()
MessageBus messageBus = new MessageBus().setUri("/null")
Logger log = null
String verticleId = ""
Vertx vertx = null
String staticConf = ""
Detailed Description
Class MessageToMap.
Parameters
<T> the generic type
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Member Function Documentation
boolean com.globo.galeb.core.bus.MessageToMap< T >.add ()
Adds the entity.
Returns
true, if successful
boolean com.globo.galeb.core.bus.MessageToMap< T >.change ()
Change the entity
Returns
true, if successful
boolean com.globo.galeb.core.bus.MessageToMap< T >.del ()
Del the entity
Returns
true, if successful
boolean com.globo.galeb.core.bus.MessageToMap< T >.reset ()
Reset the entity
Returns
true, if successful
MessageToMap<T> com.globo.galeb.core.bus.MessageToMap< T >.setLogger (final Logger log)
Sets the logger.
Parameters
log the logger
Returns
this
Referenced by com.globo.galeb.core.bus.FarmMap.add().
MessageToMap<T> com.globo.galeb.core.bus.MessageToMap< T >.setMap (final Map< String, T > map)
Sets the map.
Parameters
map the map
Returns
this
Referenced by com.globo.galeb.core.bus.FarmMap.add().
MessageToMap<T> com.globo.galeb.core.bus.MessageToMap< T >.setMessageBus (final MessageBus messageBus)
Sets the message bus.
Parameters
messageBus the message bus
Returns
this
References com.globo.galeb.core.bus.MessageBus.getEntity(), com.globo.galeb.core.bus.MessageBus.getEntityId(), com.globo.galeb.core.bus.MessageBus.getParentId(), and com.globo.galeb.core.bus.MessageBus.getUriBase().
Referenced by com.globo.galeb.core.bus.FarmMap.add().
MessageToMap<T> com.globo.galeb.core.bus.MessageToMap< T >.setVerticleId (String id)
Sets the verticle id.
Parameters
id the id
Returns
this
Referenced by com.globo.galeb.core.bus.FarmMap.add().
MessageToMap<T> com.globo.galeb.core.bus.MessageToMap< T >.setVertx (final Vertx vertx)
Sets the vertx.
Parameters
vertx the vertx
Returns
this
Referenced by com.globo.galeb.core.bus.FarmMap.add().
MessageToMap<T> com.globo.galeb.core.bus.MessageToMap< T >.staticConf (String jsonConf)
Sets static conf (from configuration file).
Parameters
jsonConf the json conf
Returns
this
Member Data Documentation
JsonObject com.globo.galeb.core.bus.MessageToMap< T >.entity = new JsonObject() protected
The entity.
Referenced by com.globo.galeb.core.bus.VirtualhostMap.add(), com.globo.galeb.core.bus.BackendMap.add(), com.globo.galeb.core.bus.FarmMap.add(), and com.globo.galeb.core.bus.BackendMap.del().
String com.globo.galeb.core.bus.MessageToMap< T >.entityId = "" protected
The entity id.
Referenced by com.globo.galeb.core.bus.VirtualhostMap.add(), com.globo.galeb.core.bus.BackendMap.add(), com.globo.galeb.core.bus.VirtualhostMap.del(), and com.globo.galeb.core.bus.BackendMap.del().
Logger com.globo.galeb.core.bus.MessageToMap< T >.log = null protected
The logger.
Referenced by com.globo.galeb.core.bus.VirtualhostMap.add(), com.globo.galeb.core.bus.BackendMap.add(), com.globo.galeb.core.bus.NullMap.add(), com.globo.galeb.core.bus.FarmMap.add(), com.globo.galeb.core.bus.NullMap.change(), com.globo.galeb.core.bus.NullMap.del(), com.globo.galeb.core.bus.VirtualhostMap.del(), com.globo.galeb.core.bus.BackendMap.del(), and com.globo.galeb.core.bus.NullMap.reset().
Map<String, T> com.globo.galeb.core.bus.MessageToMap< T >.map = new HashMap<>() protected
The map.
Referenced by com.globo.galeb.core.bus.VirtualhostMap.add(), com.globo.galeb.core.bus.BackendMap.add(), com.globo.galeb.core.bus.FarmMap.add(), com.globo.galeb.core.bus.VirtualhostMap.del(), com.globo.galeb.core.bus.BackendMap.del(), and com.globo.galeb.core.bus.FarmMap.del().
MessageBus com.globo.galeb.core.bus.MessageToMap< T >.messageBus = new MessageBus().setUri("/null") protected
The message bus.
Referenced by com.globo.galeb.core.bus.VirtualhostMap.del(), and com.globo.galeb.core.bus.BackendMap.del().
String com.globo.galeb.core.bus.MessageToMap< T >.parentId = "" protected
The parent id.
Referenced by com.globo.galeb.core.bus.BackendMap.add(), and com.globo.galeb.core.bus.BackendMap.del().
String com.globo.galeb.core.bus.MessageToMap< T >.staticConf = "" protected
The static conf.
Referenced by com.globo.galeb.core.bus.VirtualhostMap.add(), and com.globo.galeb.core.bus.FarmMap.add().
String com.globo.galeb.core.bus.MessageToMap< T >.uriBase = "" protected
The uri base.
String com.globo.galeb.core.bus.MessageToMap< T >.verticleId = "" protected
The verticle id.
Referenced by com.globo.galeb.core.bus.VirtualhostMap.add(), com.globo.galeb.core.bus.BackendMap.add(), com.globo.galeb.core.bus.FarmMap.add(), com.globo.galeb.core.bus.VirtualhostMap.del(), and com.globo.galeb.core.bus.BackendMap.del().
Vertx com.globo.galeb.core.bus.MessageToMap< T >.vertx = null protected
The vertx.
Referenced by com.globo.galeb.core.bus.VirtualhostMap.add(), and com.globo.galeb.core.bus.FarmMap.add().
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/core/bus/MessageToMap.java