Galeb: com.globo.galeb.scheduler.impl.VertxPeriodicScheduler Class Reference
com.globo.galeb.scheduler.impl.VertxPeriodicScheduler Class Reference
Public Member Functions
VertxPeriodicScheduler (Vertx vertx)
IScheduler start ()
IScheduler setHandler (ISchedulerHandler schedulerHandler)
IScheduler setPeriod (Long period)
IScheduler cancel ()
IScheduler cancelHandler (Handler< Void > cancelHandler)
IScheduler cancelFailedHandler (Handler< Void > cancelFailedHandler)
Protected Member Functions
void finalize () throws Throwable
Detailed Description
Class VertxPeriodicScheduler.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 22, 2014.
Constructor & Destructor Documentation
com.globo.galeb.scheduler.impl.VertxPeriodicScheduler.VertxPeriodicScheduler (Vertx vertx)
Instantiates a new vertx delay scheduler.
Parameters
vertx the vertx
Member Function Documentation
IScheduler com.globo.galeb.scheduler.impl.VertxPeriodicScheduler.cancel ()
Cancel the scheduler.
Returns
IScheduler
Implements com.globo.galeb.scheduler.IScheduler.
IScheduler com.globo.galeb.scheduler.impl.VertxPeriodicScheduler.cancelFailedHandler (Handler< Void > cancelFailedHandler)
Cancel failed handler.
Parameters
cancelFailedHandler the cancel failed handler
Returns
this
Implements com.globo.galeb.scheduler.IScheduler.
IScheduler com.globo.galeb.scheduler.impl.VertxPeriodicScheduler.cancelHandler (Handler< Void > cancelHandler)
Cancel handler.
Parameters
cancelHandler the cancel handler
Returns
this
Implements com.globo.galeb.scheduler.IScheduler.
void com.globo.galeb.scheduler.impl.VertxPeriodicScheduler.finalize () throws Throwable protected
IScheduler com.globo.galeb.scheduler.impl.VertxPeriodicScheduler.setHandler (ISchedulerHandler schedulerHandler)
Sets the handler.
Parameters
schedulerHandler the scheduler handler
Returns
IScheduler
Implements com.globo.galeb.scheduler.IScheduler.
Referenced by com.globo.galeb.core.BackendSession.connect().
IScheduler com.globo.galeb.scheduler.impl.VertxPeriodicScheduler.setPeriod (Long period)
Sets the scheduler period (ms).
Parameters
period the period
Returns
IScheduler
Implements com.globo.galeb.scheduler.IScheduler.
Referenced by com.globo.galeb.core.Backend.connect(), and com.globo.galeb.verticles.HealthManagerVerticle.start().
IScheduler com.globo.galeb.scheduler.impl.VertxPeriodicScheduler.start ()
Start scheduler.
Returns
IScheduler
Implements com.globo.galeb.scheduler.IScheduler.
References com.globo.galeb.scheduler.ISchedulerHandler.handle().
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/scheduler/impl/VertxPeriodicScheduler.java