Galeb: com.globo.galeb.metrics.CounterWithEventBus Class Reference
com.globo.galeb.metrics.CounterWithEventBus Class Reference
Public Member Functions
CounterWithEventBus (final EventBus eb)
void httpCode (String key, Integer code)
void httpCode (String virtualhostId, String backendId, Integer code)
void incrHttpCode (String key, Integer code)
void incrHttpCode (String key, Integer code, double sample)
void decrHttpCode (String key, Integer code)
void decrHttpCode (String key, Integer code, double sample)
void requestTime (String key, final Long initialRequestTime)
void requestTime (String virtualhostId, String backendId, Long initialRequestTime)
void sendActiveSessions (String key, Long initialRequestTime)
void sendActiveSessions (String virtualhostId, String backendId, Long initialRequestTime)
Public Member Functions inherited from com.globo.galeb.metrics.ICounter
abstract void requestTime (String key, Long initialRequestTime)
Detailed Description
Class CounterWithEventBus.
Author
See AUTHORS file.
Version
1.0.0, Nov 4, 2014.
Constructor & Destructor Documentation
com.globo.galeb.metrics.CounterWithEventBus.CounterWithEventBus (final EventBus eb)
Instantiates a new counter with statsd.
Parameters
conf the conf
vertx the vertx
log the log
Member Function Documentation
void com.globo.galeb.metrics.CounterWithEventBus.decrHttpCode (String key, Integer code)
Decrement http code count.
Parameters
key the key
code the code
Implements com.globo.galeb.metrics.ICounter.
void com.globo.galeb.metrics.CounterWithEventBus.decrHttpCode (String key, Integer code, double sample)
Decrement http code count.
Parameters
key the key
code the code
sample the sample
Implements com.globo.galeb.metrics.ICounter.
void com.globo.galeb.metrics.CounterWithEventBus.httpCode (String key, Integer code)
http code count.
Parameters
key the key
code the code
Implements com.globo.galeb.metrics.ICounter.
Referenced by com.globo.galeb.metrics.CounterWithEventBus.httpCode().
void com.globo.galeb.metrics.CounterWithEventBus.httpCode (String virtualhostId, String backendId, Integer code)
http code count.
Parameters
virtualhostId the virtualhost id
backendId the backend id
code the code
Implements com.globo.galeb.metrics.ICounter.
References com.globo.galeb.metrics.CounterWithEventBus.httpCode().
void com.globo.galeb.metrics.CounterWithEventBus.incrHttpCode (String key, Integer code)
Increment http code count.
Parameters
key the key
code the code
Implements com.globo.galeb.metrics.ICounter.
void com.globo.galeb.metrics.CounterWithEventBus.incrHttpCode (String key, Integer code, double sample)
Increment http code count.
Parameters
key the key
code the code
sample the sample
Implements com.globo.galeb.metrics.ICounter.
void com.globo.galeb.metrics.CounterWithEventBus.requestTime (String key, final Long initialRequestTime)
Referenced by com.globo.galeb.metrics.CounterWithEventBus.requestTime().
void com.globo.galeb.metrics.CounterWithEventBus.requestTime (String virtualhostId, String backendId, Long initialRequestTime)
Request time count.
Parameters
virtualhostId the virtualhost id
backendId the backend id
initialRequestTime the initial request time
Implements com.globo.galeb.metrics.ICounter.
References com.globo.galeb.metrics.CounterWithEventBus.requestTime().
void com.globo.galeb.metrics.CounterWithEventBus.sendActiveSessions (String key, Long initialRequestTime)
Send active sessions.
Parameters
key the key
initialRequestTime the initial request time
Implements com.globo.galeb.metrics.ICounter.
Referenced by com.globo.galeb.metrics.CounterWithEventBus.sendActiveSessions().
void com.globo.galeb.metrics.CounterWithEventBus.sendActiveSessions (String virtualhostId, String backendId, Long initialRequestTime)
Send active sessions.
Parameters
virtualhostId the virtualhost id
backendId the backend id
initialRequestTime the initial request time
Implements com.globo.galeb.metrics.ICounter.
References com.globo.galeb.metrics.CounterWithEventBus.sendActiveSessions().
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/metrics/CounterWithEventBus.java