Galeb: com.globo.galeb.metrics.CounterWithStatsd Class Reference
com.globo.galeb.metrics.CounterWithStatsd Class Reference
Public Member Functions
CounterWithStatsd (final JsonObject conf, final Vertx vertx, final Logger log)
void httpCode (String key, Integer code)
void httpCode (String virtualhostId, String backendId, Integer code)
void incrHttpCode (String key, Integer code)
void incrHttpCode (String key, Integer code, double sample)
void decrHttpCode (String key, Integer code)
void decrHttpCode (String key, Integer code, double sample)
void requestTime (String key, final Long initialRequestTime)
void requestTime (String virtualhostId, String backendId, Long initialRequestTime)
void sendActiveSessions (String key, Long initialRequestTime)
void sendActiveSessions (String virtualhostId, String backendId, Long initialRequestTime)
Public Member Functions inherited from com.globo.galeb.metrics.ICounter
abstract void requestTime (String key, Long initialRequestTime)
Detailed Description
Class CounterWithStatsd: send metrics to statsd
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Constructor & Destructor Documentation
com.globo.galeb.metrics.CounterWithStatsd.CounterWithStatsd (final JsonObject conf, final Vertx vertx, final Logger log)
Instantiates a new counter with statsd.
Parameters
conf the conf
vertx the vertx
log the log
Member Function Documentation
void com.globo.galeb.metrics.CounterWithStatsd.decrHttpCode (String key, Integer code)
Decrement http code count.
Parameters
key the key
code the code
Implements com.globo.galeb.metrics.ICounter.
void com.globo.galeb.metrics.CounterWithStatsd.decrHttpCode (String key, Integer code, double sample)
Decrement http code count.
Parameters
key the key
code the code
sample the sample
Implements com.globo.galeb.metrics.ICounter.
References com.globo.galeb.metrics.StatsdClient.TypeStatsdMessage.COUNT, and com.globo.galeb.metrics.StatsdClient.send().
void com.globo.galeb.metrics.CounterWithStatsd.httpCode (String key, Integer code)
http code count.
Parameters
key the key
code the code
Implements com.globo.galeb.metrics.ICounter.
References com.globo.galeb.metrics.StatsdClient.send(), and com.globo.galeb.metrics.StatsdClient.TypeStatsdMessage.TIME.
Referenced by com.globo.galeb.metrics.CounterWithStatsd.httpCode().
void com.globo.galeb.metrics.CounterWithStatsd.httpCode (String virtualhostId, String backendId, Integer code)
http code count.
Parameters
virtualhostId the virtualhost id
backendId the backend id
code the code
Implements com.globo.galeb.metrics.ICounter.
References com.globo.galeb.metrics.CounterWithStatsd.httpCode().
void com.globo.galeb.metrics.CounterWithStatsd.incrHttpCode (String key, Integer code)
Increment http code count.
Parameters
key the key
code the code
Implements com.globo.galeb.metrics.ICounter.
void com.globo.galeb.metrics.CounterWithStatsd.incrHttpCode (String key, Integer code, double sample)
Increment http code count.
Parameters
key the key
code the code
sample the sample
Implements com.globo.galeb.metrics.ICounter.
References com.globo.galeb.metrics.StatsdClient.TypeStatsdMessage.COUNT, and com.globo.galeb.metrics.StatsdClient.send().
void com.globo.galeb.metrics.CounterWithStatsd.requestTime (String key, final Long initialRequestTime)
References com.globo.galeb.metrics.StatsdClient.send(), and com.globo.galeb.metrics.StatsdClient.TypeStatsdMessage.TIME.
Referenced by com.globo.galeb.metrics.CounterWithStatsd.requestTime().
void com.globo.galeb.metrics.CounterWithStatsd.requestTime (String virtualhostId, String backendId, Long initialRequestTime)
Request time count.
Parameters
virtualhostId the virtualhost id
backendId the backend id
initialRequestTime the initial request time
Implements com.globo.galeb.metrics.ICounter.
References com.globo.galeb.metrics.CounterWithStatsd.requestTime().
void com.globo.galeb.metrics.CounterWithStatsd.sendActiveSessions (String key, Long initialRequestTime)
Send active sessions.
Parameters
key the key
initialRequestTime the initial request time
Implements com.globo.galeb.metrics.ICounter.
References com.globo.galeb.metrics.StatsdClient.TypeStatsdMessage.COUNT, and com.globo.galeb.metrics.StatsdClient.send().
Referenced by com.globo.galeb.metrics.CounterWithStatsd.sendActiveSessions().
void com.globo.galeb.metrics.CounterWithStatsd.sendActiveSessions (String virtualhostId, String backendId, Long initialRequestTime)
Send active sessions.
Parameters
virtualhostId the virtualhost id
backendId the backend id
initialRequestTime the initial request time
Implements com.globo.galeb.metrics.ICounter.
References com.globo.galeb.metrics.CounterWithStatsd.sendActiveSessions().
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/metrics/CounterWithStatsd.java