Galeb: com.globo.galeb.core.ManagerService Class Reference
com.globo.galeb.core.ManagerService Class Reference
Classes
enum UriSupported
Public Member Functions
ManagerService (String id, final Logger log)
ManagerService setRequest (final HttpServerRequest req)
ManagerService setResponse (final ServerResponse resp)
boolean checkUriOk ()
boolean checkMethodOk (String methodId)
boolean checkIdConsistency (JsonObject entityJson, String idFromUri)
String getRequestId ()
boolean checkIdPresent ()
boolean endResponse (int statusCode, String message)
int statusFromMessageSchema (String message, String uri, boolean registerLog)
int statusFromMessageSchema (String message, String uri)
Detailed Description
Class ManagerService.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Constructor & Destructor Documentation
com.globo.galeb.core.ManagerService.ManagerService (String id, final Logger log)
Instantiates a new manager service.
Parameters
id the id
log the log
Member Function Documentation
boolean com.globo.galeb.core.ManagerService.checkIdConsistency (JsonObject entityJson, String idFromUri)
Check if id is consistency.
Parameters
entityJson the entity json
idFromUri the id from uri
Returns
true, if successful
References com.globo.galeb.core.HttpCode.BAD_REQUEST, com.globo.galeb.core.ManagerService.endResponse(), and com.globo.galeb.core.IJsonable.ID_FIELDNAME.
Referenced by com.globo.galeb.handlers.rest.DeleteMatcherHandler.handle(), and com.globo.galeb.handlers.rest.PutMatcherHandler.handle().
boolean com.globo.galeb.core.ManagerService.checkIdPresent ()
Check if id is present.
Returns
true, if successful
References com.globo.galeb.core.HttpCode.BAD_REQUEST, com.globo.galeb.core.ManagerService.endResponse(), and com.globo.galeb.core.ManagerService.getRequestId().
Referenced by com.globo.galeb.handlers.rest.PutMatcherHandler.handle().
boolean com.globo.galeb.core.ManagerService.checkMethodOk (String methodId)
Check if method is ok.
Parameters
methodId the method id
Returns
true, if successful
References com.globo.galeb.core.ManagerService.endResponse(), and com.globo.galeb.core.HttpCode.METHOD_NOT_ALLOWED.
Referenced by com.globo.galeb.handlers.rest.DeleteMatcherHandler.handle(), com.globo.galeb.handlers.rest.PutMatcherHandler.handle(), and com.globo.galeb.handlers.rest.PostMatcherHandler.handle().
boolean com.globo.galeb.core.ManagerService.checkUriOk ()
Check if uri is ok.
Returns
true, if successful
References com.globo.galeb.core.ManagerService.endResponse(), and com.globo.galeb.core.HttpCode.NOT_FOUND.
Referenced by com.globo.galeb.handlers.rest.DeleteMatcherHandler.handle(), com.globo.galeb.handlers.rest.PutMatcherHandler.handle(), com.globo.galeb.handlers.rest.PostMatcherHandler.handle(), and com.globo.galeb.handlers.rest.GetMatcherHandler.handle().
boolean com.globo.galeb.core.ManagerService.endResponse (int statusCode, String message)
End response.
Parameters
statusCode the status code
message the message
Returns
true, if successful
References com.globo.galeb.core.HttpCode.BAD_REQUEST, com.globo.galeb.core.ServerResponse.endResponse(), com.globo.galeb.core.HttpCode.getMessage(), com.globo.galeb.core.ServerResponse.setMessage(), and com.globo.galeb.core.ServerResponse.setStatusCode().
Referenced by com.globo.galeb.core.ManagerService.checkIdConsistency(), com.globo.galeb.core.ManagerService.checkIdPresent(), com.globo.galeb.core.ManagerService.checkMethodOk(), and com.globo.galeb.core.ManagerService.checkUriOk().
String com.globo.galeb.core.ManagerService.getRequestId ()
Gets the request id.
Returns
the request id
References com.globo.galeb.core.IJsonable.ID_FIELDNAME.
Referenced by com.globo.galeb.core.ManagerService.checkIdPresent().
ManagerService com.globo.galeb.core.ManagerService.setRequest (final HttpServerRequest req)
Sets the httpServerRequest.
Parameters
req the httpServerRequest
Returns
this
Referenced by com.globo.galeb.handlers.rest.DeleteMatcherHandler.handle(), com.globo.galeb.handlers.rest.PutMatcherHandler.handle(), com.globo.galeb.handlers.rest.PostMatcherHandler.handle(), and com.globo.galeb.handlers.rest.GetMatcherHandler.handle().
ManagerService com.globo.galeb.core.ManagerService.setResponse (final ServerResponse resp)
Sets the serverResponse.
Parameters
resp the serverResponse
Returns
this
Referenced by com.globo.galeb.handlers.rest.DeleteMatcherHandler.handle(), com.globo.galeb.handlers.rest.PutMatcherHandler.handle(), com.globo.galeb.handlers.rest.PostMatcherHandler.handle(), and com.globo.galeb.handlers.rest.GetMatcherHandler.handle().
int com.globo.galeb.core.ManagerService.statusFromMessageSchema (String message, String uri, boolean registerLog)
Status from message schema.
Parameters
message the message
uri the uri
registerLog the register log
Returns
http status code
References com.globo.galeb.core.HttpCode.BAD_REQUEST, com.globo.galeb.core.IJsonable.ID_FIELDNAME, and com.globo.galeb.core.HttpCode.OK.
Referenced by com.globo.galeb.handlers.rest.DeleteMatcherHandler.handle(), com.globo.galeb.handlers.rest.PutMatcherHandler.handle(), com.globo.galeb.handlers.rest.PostMatcherHandler.handle(), and com.globo.galeb.core.ManagerService.statusFromMessageSchema().
int com.globo.galeb.core.ManagerService.statusFromMessageSchema (String message, String uri)
Status from message schema.
Parameters
message the message
uri the uri
Returns
http status code
References com.globo.galeb.core.ManagerService.statusFromMessageSchema().
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/core/ManagerService.java