Galeb: com.globo.galeb.streams.Pump Class Reference
com.globo.galeb.streams.Pump Class Reference
Public Member Functions
Pump (ReadStream<?> rs, WriteStream<?> ws)
Pump (ReadStream<?> rs, WriteStream<?> ws, int maxWriteQueueSize)
void start ()
void stop ()
int bytesPumped ()
Pump exceptionHandler (Handler< Throwable > exceptionHandler)
Pump writeHandler (Handler< Void > writeHandler)
Detailed Description
Class Pump.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 22, 2014.
Constructor & Destructor Documentation
com.globo.galeb.streams.Pump.Pump (ReadStream<?> rs, WriteStream<?> ws)
Instantiates a new pump.
Parameters
rs ReadStream
ws WriteStream
com.globo.galeb.streams.Pump.Pump (ReadStream<?> rs, WriteStream<?> ws, int maxWriteQueueSize)
Instantiates a new pump.
Parameters
rs ReadStream
ws WriteStream
maxWriteQueueSize the max write queue size
Member Function Documentation
int com.globo.galeb.streams.Pump.bytesPumped ()
Return the total number of bytes pumped by this pump.
Returns
bytes pumped
Referenced by com.globo.galeb.handlers.RouterResponseHandler.handle().
Pump com.globo.galeb.streams.Pump.exceptionHandler (Handler< Throwable > exceptionHandler)
Exception handler.
Parameters
exceptionHandler the exception handler
Returns
this
void com.globo.galeb.streams.Pump.start ()
Start the Pump. The Pump can be started and stopped multiple times.
Referenced by com.globo.galeb.handlers.RouterResponseHandler.handle(), and com.globo.galeb.handlers.RouterRequestHandler.handle().
void com.globo.galeb.streams.Pump.stop ()
Stop the Pump. The Pump can be started and stopped multiple times.
Pump com.globo.galeb.streams.Pump.writeHandler (Handler< Void > writeHandler)
Write handler.
Parameters
writeHandler the write handler
Returns
this
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/streams/Pump.java