Galeb: com.globo.galeb.core.bus.VertxQueueService Class Reference
com.globo.galeb.core.bus.VertxQueueService Class Reference
Public Member Functions
VertxQueueService (final EventBus eb, final Logger log)
void queueToAdd (JsonObject json, final String uri)
void queueToDel (JsonObject json, final String uri)
void queueToChange (JsonObject json, final String uri)
void registerHealthcheck (final ICallbackHealthcheck callbackHealthcheck)
void publishBackendOk (String backend)
void publishBackendFail (String backendId)
void publishBackendConnections (String queueActiveConnections, JsonObject myConnections)
void registerConnectionsCounter (final ICallbackConnectionCounter connectionsCounter, String queueActiveConnections)
void publishActiveConnections (String queueActiveConnections, JsonObject myConnections)
void unregisterConnectionsCounter (final ICallbackConnectionCounter connectionsCounter, String queueActiveConnections)
void registerQueueAdd (final Object starter, final ICallbackQueueAction callbackQueueAction)
void registerQueueDel (final Object starter, final ICallbackQueueAction callbackQueueAction)
void registerQueueVersion (final Object starter, final ICallbackQueueAction callbackQueueAction)
void registerUpdateSharedData (final Object starter, final ICallbackSharedData callbackSharedData)
void updateSharedData ()
Public Member Functions inherited from com.globo.galeb.core.bus.IQueueService
void queueToAdd (JsonObject json, String uri)
void queueToDel (JsonObject json, String uri)
void queueToChange (JsonObject json, String uri)
void registerHealthcheck (ICallbackHealthcheck callbackHealthcheck)
void registerConnectionsCounter (ICallbackConnectionCounter connectionsCounter, String queueActiveConnections)
void unregisterConnectionsCounter (ICallbackConnectionCounter connectionsCounter, String queueActiveConnections)
void registerQueueAdd (Object starter, ICallbackQueueAction callbackQueueAction)
void registerQueueDel (Object starter, ICallbackQueueAction callbackQueueAction)
void registerQueueVersion (Object starter, ICallbackQueueAction callbackQueueAction)
void registerUpdateSharedData (Object starter, ICallbackSharedData callbackSharedData)
Additional Inherited Members
Static Public Attributes inherited from com.globo.galeb.core.bus.IQueueService
static final String QUEUE_HEALTHCHECK_OK = "healthcheck.ok"
static final String QUEUE_HEALTHCHECK_FAIL = "healthcheck.fail"
static final String QUEUE_BACKEND_CONNECTIONS_PREFIX = "conn_"
Detailed Description
Class VertxQueueService.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Constructor & Destructor Documentation
com.globo.galeb.core.bus.VertxQueueService.VertxQueueService (final EventBus eb, final Logger log)
Instantiates a new vertxQueueService.
Parameters
eb the eb
log the log
Member Function Documentation
void com.globo.galeb.core.bus.VertxQueueService.publishActiveConnections (String queueActiveConnections, JsonObject myConnections)
Publish active connections.
Parameters
queueActiveConnections the queue active connections
myConnections the local connections
Implements com.globo.galeb.core.bus.IQueueService.
void com.globo.galeb.core.bus.VertxQueueService.publishBackendConnections (String queueActiveConnections, JsonObject myConnections)
Publish backend connections.
Parameters
queueActiveConnections the queue active connections
myConnections the local connections
Implements com.globo.galeb.core.bus.IQueueService.
void com.globo.galeb.core.bus.VertxQueueService.publishBackendFail (String backend)
Publish backendFail.
Parameters
backend the backend
Implements com.globo.galeb.core.bus.IQueueService.
References com.globo.galeb.core.bus.IQueueService.QUEUE_HEALTHCHECK_FAIL.
void com.globo.galeb.core.bus.VertxQueueService.publishBackendOk (String backend)
Publish backendOk.
Parameters
backend the backend
Implements com.globo.galeb.core.bus.IQueueService.
References com.globo.galeb.core.bus.IQueueService.QUEUE_HEALTHCHECK_OK.
void com.globo.galeb.core.bus.VertxQueueService.queueToAdd (JsonObject json, final String uri)
References com.globo.galeb.core.bus.IQueueService.ACTION.ADD.
void com.globo.galeb.core.bus.VertxQueueService.queueToChange (JsonObject json, final String uri)
void com.globo.galeb.core.bus.VertxQueueService.queueToDel (JsonObject json, final String uri)
References com.globo.galeb.core.bus.IQueueService.ACTION.DEL.
void com.globo.galeb.core.bus.VertxQueueService.registerConnectionsCounter (final ICallbackConnectionCounter connectionsCounter, String queueActiveConnections)
References com.globo.galeb.core.bus.ICallbackConnectionCounter.isRegistered(), and com.globo.galeb.core.bus.ICallbackConnectionCounter.setRegistered().
void com.globo.galeb.core.bus.VertxQueueService.registerHealthcheck (final ICallbackHealthcheck callbackHealthcheck)
References com.globo.galeb.core.bus.IQueueService.QUEUE_HEALTHCHECK_OK.
void com.globo.galeb.core.bus.VertxQueueService.registerQueueAdd (final Object starter, final ICallbackQueueAction callbackQueueAction)
References com.globo.galeb.core.bus.ICallbackQueueAction.addToMap().
void com.globo.galeb.core.bus.VertxQueueService.registerQueueDel (final Object starter, final ICallbackQueueAction callbackQueueAction)
References com.globo.galeb.core.bus.ICallbackQueueAction.delFromMap().
void com.globo.galeb.core.bus.VertxQueueService.registerQueueVersion (final Object starter, final ICallbackQueueAction callbackQueueAction)
References com.globo.galeb.core.bus.ICallbackQueueAction.setVersion().
void com.globo.galeb.core.bus.VertxQueueService.registerUpdateSharedData (final Object starter, final ICallbackSharedData callbackSharedData)
References com.globo.galeb.core.bus.ICallbackSharedData.updateSharedData().
void com.globo.galeb.core.bus.VertxQueueService.unregisterConnectionsCounter (final ICallbackConnectionCounter connectionsCounter, String queueActiveConnections)
References com.globo.galeb.core.bus.ICallbackConnectionCounter.isRegistered(), and com.globo.galeb.core.bus.ICallbackConnectionCounter.setRegistered().
void com.globo.galeb.core.bus.VertxQueueService.updateSharedData ()
Update shared data.
Implements com.globo.galeb.core.bus.IQueueService.
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/core/bus/VertxQueueService.java