Galeb: com.globo.galeb.handlers.ws.BackendWebSocketHandler Class Reference
com.globo.galeb.handlers.ws.BackendWebSocketHandler Class Reference
Public Member Functions
BackendWebSocketHandler (final Vertx vertx, final Logger log, final String backendId, final ServerWebSocket serverWebSocket)
void handle (final WebSocket websocket)
void writeWebSocket (final WebSocket ws, final Queue< Buffer > messages)
void writeWebSocket (final WebSocket ws, Buffer message)
void writeServerWebSocket (Buffer buffer)
Long getInitialRequestTime ()
BackendWebSocketHandler setInitialRequestTime (Long initialRequestTime)
void forwardToBackend (Buffer buffer)
void closeWS ()
Detailed Description
Class BackendWebSocketHandler.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Constructor & Destructor Documentation
com.globo.galeb.handlers.ws.BackendWebSocketHandler.BackendWebSocketHandler (final Vertx vertx, final Logger log, final String backendId, final ServerWebSocket serverWebSocket)
Instantiates a new backend web socket handler.
Parameters
vertx the vertx
log the log
backendId the backend id
serverWebSocket the server web socket
Member Function Documentation
void com.globo.galeb.handlers.ws.BackendWebSocketHandler.closeWS ()
Close websocket.
Referenced by com.globo.galeb.handlers.ws.FrontendWebSocketHandler.handle().
void com.globo.galeb.handlers.ws.BackendWebSocketHandler.forwardToBackend (Buffer buffer)
Forward to backend.
Parameters
buffer the buffer
References com.globo.galeb.handlers.ws.BackendWebSocketHandler.writeWebSocket().
Referenced by com.globo.galeb.handlers.ws.FrontendWebSocketHandler.handle().
Long com.globo.galeb.handlers.ws.BackendWebSocketHandler.getInitialRequestTime ()
Gets the initial request time.
Returns
the initial request time
void com.globo.galeb.handlers.ws.BackendWebSocketHandler.handle (final WebSocket websocket)
References com.globo.galeb.core.bus.IQueueService.QUEUE_HEALTHCHECK_FAIL, com.globo.galeb.handlers.ws.BackendWebSocketHandler.writeServerWebSocket(), and com.globo.galeb.handlers.ws.BackendWebSocketHandler.writeWebSocket().
Referenced by com.globo.galeb.handlers.ws.BackendWebSocketHandler.writeServerWebSocket(), and com.globo.galeb.handlers.ws.BackendWebSocketHandler.writeWebSocket().
BackendWebSocketHandler com.globo.galeb.handlers.ws.BackendWebSocketHandler.setInitialRequestTime (Long initialRequestTime)
Sets the initial request time.
Parameters
initialRequestTime the initial request time
Returns
the backend web socket handler
void com.globo.galeb.handlers.ws.BackendWebSocketHandler.writeServerWebSocket (Buffer buffer)
Write websocket (server side).
Parameters
buffer the buffer
References com.globo.galeb.handlers.ws.BackendWebSocketHandler.handle().
Referenced by com.globo.galeb.handlers.ws.BackendWebSocketHandler.handle().
void com.globo.galeb.handlers.ws.BackendWebSocketHandler.writeWebSocket (final WebSocket ws, final Queue< Buffer > messages)
Write websocket.
Parameters
ws the websocket
messages the messages queue
Referenced by com.globo.galeb.handlers.ws.BackendWebSocketHandler.forwardToBackend(), and com.globo.galeb.handlers.ws.BackendWebSocketHandler.handle().
void com.globo.galeb.handlers.ws.BackendWebSocketHandler.writeWebSocket (final WebSocket ws, Buffer message)
Write websocket.
Parameters
ws the websocket
message the message (buffer)
References com.globo.galeb.handlers.ws.BackendWebSocketHandler.handle().
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/handlers/ws/BackendWebSocketHandler.java