Galeb: com.globo.galeb.core.Virtualhost Class Reference
com.globo.galeb.core.Virtualhost Class Reference
Public Member Functions
Virtualhost (JsonObject json, final Vertx vertx)
String toString ()
void setQueue (final IQueueService queueService)
boolean addBackend (String backend, boolean backendOk)
boolean addBackend (JsonObject backendJson, boolean backendOk)
UniqueArrayList< Backend > getBackends (boolean backendOk)
String getVirtualhostName ()
Boolean removeBackend (String backend, boolean backendOk)
void clear (boolean backendOk)
void clearAll ()
Backend getChoice (RequestData requestData)
Virtualhost setLoadBalancePolicy (String loadBalancePolicyName)
ILoadBalancePolicy getLoadBalancePolicy ()
ILoadBalancePolicy loadBalancePolicyClassLoader (String loadBalancePolicyName)
boolean hasBackends ()
boolean hasBadBackends ()
JsonObject toJson ()
void setTransientState ()
Long getRequestTimeOut ()
Virtualhost setStaticConf (String staticConf)
Boolean isChunked ()
Boolean hasAccessLog ()
Public Member Functions inherited from com.globo.galeb.core.Entity
JsonObject getProperties ()
Entity setStaticConf (String staticConf)
JsonObject toJson ()
Static Public Attributes
static final String BACKENDS_FIELDNAME = "backends"
static final String BACKENDS_ELIGIBLE_FIELDNAME = "eligible"
static final String BACKENDS_FAILED_FIELDNAME = "failed"
static final String LOADBALANCE_POLICY_FIELDNAME = "loadBalancePolicy"
static final String REQUEST_TIMEOUT_FIELDNAME = "requestTimeOut"
static final String ENABLE_CHUNCKED_FIELDNAME = "enableChunked"
static final String ENABLE_ACCESSLOG_FIELDNAME = "enableAccessLog"
static final String TRANSIENT_STATE_FIELDNAME = "_transientState"
Static Public Attributes inherited from com.globo.galeb.core.IJsonable
static final String ID_FIELDNAME = "id"
static final String PARENT_ID_FIELDNAME = "parentId"
static final String PROPERTIES_FIELDNAME = "properties"
static final String STATUS_FIELDNAME = "_status"
static final String CREATED_AT_FIELDNAME = "_created_at"
static final String MODIFIED_AT_FIELDNAME = "_modified_at"
static final String LINKS_FIELDNAME = "_links"
static final String LINKS_REL_FIELDNAME = "rel"
static final String LINKS_HREF_FIELDNAME = "href"
Additional Inherited Members
Protected Member Functions inherited from com.globo.galeb.core.Entity
Entity prepareJson ()
Protected Attributes inherited from com.globo.galeb.core.Entity
JsonObject staticConf = new JsonObject()
String id = ""
final Long createdAt = System.currentTimeMillis()
Long modifiedAt = System.currentTimeMillis()
final JsonObject properties = new JsonObject()
final JsonObject idObj = new JsonObject()
String entityType = this.getClass().getSimpleName().toLowerCase()
Detailed Description
Class Virtualhost.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Constructor & Destructor Documentation
com.globo.galeb.core.Virtualhost.Virtualhost (JsonObject json, final Vertx vertx)
Instantiates a new virtualhost.
Parameters
json the json properties
vertx the vertx
References com.globo.galeb.core.Virtualhost.getLoadBalancePolicy(), com.globo.galeb.core.IJsonable.ID_FIELDNAME, com.globo.galeb.core.Entity.properties, and com.globo.galeb.core.IJsonable.PROPERTIES_FIELDNAME.
Member Function Documentation
boolean com.globo.galeb.core.Virtualhost.addBackend (String backend, boolean backendOk)
Adds a backend.
Parameters
backend the backend
backendOk the backend ok
Returns
true, if successful
References com.globo.galeb.core.IJsonable.ID_FIELDNAME.
Referenced by com.globo.galeb.core.bus.BackendMap.add().
boolean com.globo.galeb.core.Virtualhost.addBackend (JsonObject backendJson, boolean backendOk)
Adds a backend.
Parameters
backendJson the backend json
backendOk the backend ok
Returns
true, if successful
References com.globo.galeb.core.Backend.setKeepAliveMaxRequest(), com.globo.galeb.core.Backend.setKeepAliveTimeOut(), com.globo.galeb.core.Backend.setMaxPoolSize(), com.globo.galeb.core.Backend.setMinSessionPoolSize(), com.globo.galeb.core.Backend.setQueueService(), com.globo.galeb.core.Virtualhost.setTransientState(), and com.globo.galeb.core.Backend.startSessionPool().
void com.globo.galeb.core.Virtualhost.clear (boolean backendOk)
Clear backends (filtered to backendOk).
Parameters
backendOk the backend ok
References com.globo.galeb.core.Virtualhost.setTransientState().
void com.globo.galeb.core.Virtualhost.clearAll ()
Clear all backends.
References com.globo.galeb.core.Virtualhost.setTransientState().
UniqueArrayList<Backend> com.globo.galeb.core.Virtualhost.getBackends (boolean backendOk)
Gets backends.
Parameters
backendOk the backend ok
Returns
the backends
Referenced by com.globo.galeb.verticles.HealthManagerVerticle.moveBackend().
Backend com.globo.galeb.core.Virtualhost.getChoice (RequestData requestData)
Gets the backend chosen.
Parameters
requestData the request data
Returns
the choice
References com.globo.galeb.loadbalance.ILoadBalancePolicy.getChoice(), com.globo.galeb.core.Virtualhost.getLoadBalancePolicy(), com.globo.galeb.core.Entity.properties, and com.globo.galeb.core.RequestData.setProperties().
Referenced by com.globo.galeb.handlers.ws.FrontendWebSocketHandler.handle(), and com.globo.galeb.handlers.RouterRequestHandler.handle().
ILoadBalancePolicy com.globo.galeb.core.Virtualhost.getLoadBalancePolicy ()
Gets the load balance policy.
Returns
the load balance policy
References com.globo.galeb.loadbalance.ILoadBalancePolicy.isDefault(), com.globo.galeb.core.Virtualhost.loadBalancePolicyClassLoader(), com.globo.galeb.core.Entity.properties, and com.globo.galeb.loadbalance.ILoadBalancePolicy.toString().
Referenced by com.globo.galeb.core.Virtualhost.getChoice(), and com.globo.galeb.core.Virtualhost.Virtualhost().
Long com.globo.galeb.core.Virtualhost.getRequestTimeOut ()
Gets the request time out.
Returns
the request time out
Referenced by com.globo.galeb.handlers.RouterRequestHandler.handle().
String com.globo.galeb.core.Virtualhost.getVirtualhostName ()
Gets the virtualhost name.
Returns
the virtualhost name
References com.globo.galeb.core.Entity.id.
Referenced by com.globo.galeb.core.Virtualhost.toString().
Boolean com.globo.galeb.core.Virtualhost.hasAccessLog ()
Checks if access log is enabled.
Returns
true, if enabled
References com.globo.galeb.core.Entity.properties.
Referenced by com.globo.galeb.handlers.RouterRequestHandler.handle().
boolean com.globo.galeb.core.Virtualhost.hasBackends ()
Checks if has backends.
Returns
true, if successful
Referenced by com.globo.galeb.handlers.ws.FrontendWebSocketHandler.handle(), and com.globo.galeb.handlers.RouterRequestHandler.handle().
boolean com.globo.galeb.core.Virtualhost.hasBadBackends ()
Checks if has bad backends.
Returns
true, if successful
Boolean com.globo.galeb.core.Virtualhost.isChunked ()
Checks if is chunked.
Returns
true, if chunked
References com.globo.galeb.core.Entity.properties.
ILoadBalancePolicy com.globo.galeb.core.Virtualhost.loadBalancePolicyClassLoader (String loadBalancePolicyName)
Load balance policy class loader.
Parameters
loadBalancePolicyName the load balance policy name
Returns
load balance policy instance
Referenced by com.globo.galeb.core.Virtualhost.getLoadBalancePolicy().
Boolean com.globo.galeb.core.Virtualhost.removeBackend (String backend, boolean backendOk)
Removes a backend.
Parameters
backend the backend
backendOk the backend ok
Returns
the boolean
References com.globo.galeb.core.Virtualhost.setTransientState().
Referenced by com.globo.galeb.core.bus.BackendMap.del().
Virtualhost com.globo.galeb.core.Virtualhost.setLoadBalancePolicy (String loadBalancePolicyName)
Sets the load balance policy.
Parameters
loadBalancePolicyName the load balance policy name
Returns
this
References com.globo.galeb.core.Virtualhost.LOADBALANCE_POLICY_FIELDNAME, and com.globo.galeb.core.Entity.properties.
void com.globo.galeb.core.Virtualhost.setQueue (final IQueueService queueService)
Sets the queueService.
Parameters
queueService the queue service instance
Referenced by com.globo.galeb.handlers.RouterRequestHandler.handle().
Virtualhost com.globo.galeb.core.Virtualhost.setStaticConf (String staticConf)
References com.globo.galeb.core.Backend.KEEPALIVE_MAXREQUEST_FIELDNAME, com.globo.galeb.core.Backend.KEEPALIVE_TIMEOUT_FIELDNAME, com.globo.galeb.core.Backend.MAXPOOL_SIZE_FIELDNAME, com.globo.galeb.core.Backend.MIN_SESSION_POOL_SIZE_FIELDNAME, and com.globo.galeb.core.Virtualhost.setStaticConf().
Referenced by com.globo.galeb.core.Virtualhost.setStaticConf().
void com.globo.galeb.core.Virtualhost.setTransientState ()
Sets transient state.
References com.globo.galeb.core.Entity.idObj.
Referenced by com.globo.galeb.core.Virtualhost.addBackend(), com.globo.galeb.core.Virtualhost.clear(), com.globo.galeb.core.Virtualhost.clearAll(), and com.globo.galeb.core.Virtualhost.removeBackend().
JsonObject com.globo.galeb.core.Virtualhost.toJson ()
json representation of the Entity.
Returns
the json object
Implements com.globo.galeb.core.IJsonable.
References com.globo.galeb.core.Entity.idObj, com.globo.galeb.core.Backend.KEEPALIVE_MAXREQUEST_FIELDNAME, com.globo.galeb.core.Backend.KEEPALIVE_TIMEOUT_FIELDNAME, com.globo.galeb.core.Backend.MAXPOOL_SIZE_FIELDNAME, com.globo.galeb.core.Backend.MIN_SESSION_POOL_SIZE_FIELDNAME, com.globo.galeb.core.Entity.prepareJson(), and com.globo.galeb.core.Entity.properties.
Referenced by com.globo.galeb.verticles.HealthManagerVerticle.moveBackend(), and com.globo.galeb.core.Farm.toJson().
String com.globo.galeb.core.Virtualhost.toString ()
References com.globo.galeb.core.Virtualhost.getVirtualhostName().
Member Data Documentation
final String com.globo.galeb.core.Virtualhost.BACKENDS_ELIGIBLE_FIELDNAME = "eligible" static
The Constant BACKENDS_ELIGIBLE_FIELDNAME.
Referenced by com.globo.galeb.core.bus.FarmMap.add().
final String com.globo.galeb.core.Virtualhost.BACKENDS_FAILED_FIELDNAME = "failed" static
The Constant BACKENDS_FAILED_FIELDNAME.
final String com.globo.galeb.core.Virtualhost.BACKENDS_FIELDNAME = "backends" static
The Constant BACKENDS_FIELDNAME.
Referenced by com.globo.galeb.core.bus.FarmMap.add().
final String com.globo.galeb.core.Virtualhost.ENABLE_ACCESSLOG_FIELDNAME = "enableAccessLog" static
The Constant ENABLE_ACCESSLOG_FIELDNAME.
final String com.globo.galeb.core.Virtualhost.ENABLE_CHUNCKED_FIELDNAME = "enableChunked" static
The Constant ENABLE_CHUNCKED_FIELDNAME.
final String com.globo.galeb.core.Virtualhost.LOADBALANCE_POLICY_FIELDNAME = "loadBalancePolicy" static
The Constant LOADBALANCE_POLICY_FIELDNAME.
Referenced by com.globo.galeb.core.Virtualhost.setLoadBalancePolicy().
final String com.globo.galeb.core.Virtualhost.REQUEST_TIMEOUT_FIELDNAME = "requestTimeOut" static
The Constant REQUEST_TIMEOUT_FIELDNAME.
final String com.globo.galeb.core.Virtualhost.TRANSIENT_STATE_FIELDNAME = "_transientState" static
The Constant TRANSIENT_STATE_FIELDNAME.
Referenced by com.globo.galeb.loadbalance.impl.LeastConnPolicy.getChoice(), and com.globo.galeb.loadbalance.impl.HashPolicy.getChoice().
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/core/Virtualhost.java