Galeb: com.globo.galeb.loadbalance.impl.LeastConnPolicy Class Reference
com.globo.galeb.loadbalance.impl.LeastConnPolicy Class Reference
Public Member Functions
Backend getChoice (final List< Backend > backends, final RequestData requestData)
boolean isDefault ()
String toString ()
Additional Inherited Members
Static Public Attributes inherited from com.globo.galeb.loadbalance.ILoadBalancePolicy
static final String CACHE_TIMEOUT_FIELDNAME = "cacheTimeout"
Detailed Description
Class LeastConnPolicy.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Member Function Documentation
Backend com.globo.galeb.loadbalance.impl.LeastConnPolicy.getChoice (final List< Backend > backends, final RequestData requestData)
Gets the choice.
Parameters
backends backends collection
requestData the request data
Returns
the backend chosen
Implements com.globo.galeb.loadbalance.ILoadBalancePolicy.
References com.globo.galeb.loadbalance.ILoadBalancePolicy.CACHE_TIMEOUT_FIELDNAME, com.globo.galeb.loadbalance.impl.LeastConnectionsFinder.get(), com.globo.galeb.core.RequestData.getProperties(), com.globo.galeb.loadbalance.impl.LeastConnectionsFinder.rebuild(), com.globo.galeb.core.Virtualhost.TRANSIENT_STATE_FIELDNAME, and com.globo.galeb.loadbalance.impl.LeastConnectionsFinder.update().
boolean com.globo.galeb.loadbalance.impl.LeastConnPolicy.isDefault ()
Checks if is default.
Returns
true, if is default
Implements com.globo.galeb.loadbalance.ILoadBalancePolicy.
String com.globo.galeb.loadbalance.impl.LeastConnPolicy.toString ()
Loadbalance string name
Returns
the loadbalance string name
Implements com.globo.galeb.loadbalance.ILoadBalancePolicy.
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/loadbalance/impl/LeastConnPolicy.java