Galeb: com.globo.galeb.core.ServerResponse Class Reference
com.globo.galeb.core.ServerResponse Class Reference
Public Member Functions
ServerResponse (final HttpServerRequest req, final Logger log, final ICounter counter, boolean enableAccessLog)
ServerResponse setId (String id)
ServerResponse setBackendId (String backendId)
ServerResponse setHeaderHost (String headerHost)
ServerResponse setMessage (final String message)
ServerResponse setStatusCode (Integer code)
ServerResponse setHeaders (final MultiMap headers)
void showErrorAndClose (final Throwable event)
void closeResponse () throws RuntimeException
void endResponse ()
void logRequest ()
void sendRequestCount ()
void setChunked (Boolean enableChunked)
Detailed Description
Class ServerResponse.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Constructor & Destructor Documentation
com.globo.galeb.core.ServerResponse.ServerResponse (final HttpServerRequest req, final Logger log, final ICounter counter, boolean enableAccessLog)
Instantiates a new server response.
Parameters
req the req
log the log
counter the counter
enableAccessLog the enable access log
References com.globo.galeb.core.ServerResponse.showErrorAndClose().
Member Function Documentation
void com.globo.galeb.core.ServerResponse.closeResponse () throws RuntimeException
Close response.
Referenced by com.globo.galeb.handlers.RouterResponseHandler.handle(), and com.globo.galeb.core.ServerResponse.showErrorAndClose().
void com.globo.galeb.core.ServerResponse.endResponse ()
Finish the connection.
References com.globo.galeb.core.ServerResponse.logRequest(), and com.globo.galeb.core.ServerResponse.sendRequestCount().
Referenced by com.globo.galeb.core.ManagerService.endResponse(), com.globo.galeb.handlers.rest.PostMatcherHandler.handle(), com.globo.galeb.handlers.rest.PutMatcherHandler.handle(), com.globo.galeb.handlers.rest.DeleteMatcherHandler.handle(), com.globo.galeb.handlers.rest.GetMatcherHandler.handle(), com.globo.galeb.handlers.RouterResponseHandler.handle(), and com.globo.galeb.core.ServerResponse.showErrorAndClose().
void com.globo.galeb.core.ServerResponse.logRequest ()
Log the request.
References com.globo.galeb.logger.HttpLogFormatter.getFormatedLog(), com.globo.galeb.core.HttpCode.isServerError(), and com.globo.galeb.logger.impl.NcsaLogExtendedFormatter.setRequestData().
Referenced by com.globo.galeb.core.ServerResponse.endResponse().
void com.globo.galeb.core.ServerResponse.sendRequestCount ()
Send request count to counter.
References com.globo.galeb.metrics.ICounter.httpCode(), and com.globo.galeb.core.HttpCode.INTERNAL_SERVER_ERROR.
Referenced by com.globo.galeb.core.ServerResponse.endResponse().
ServerResponse com.globo.galeb.core.ServerResponse.setBackendId (String backendId)
Sets the backend id.
Parameters
backendId the backend id
Returns
this
Referenced by com.globo.galeb.handlers.RouterResponseHandler.handle().
void com.globo.galeb.core.ServerResponse.setChunked (Boolean enableChunked)
Referenced by com.globo.galeb.handlers.RouterRequestHandler.handle().
ServerResponse com.globo.galeb.core.ServerResponse.setHeaderHost (String headerHost)
Sets the header host.
Parameters
headerHost the header host
Returns
this
Referenced by com.globo.galeb.handlers.RouterResponseHandler.handle().
ServerResponse com.globo.galeb.core.ServerResponse.setHeaders (final MultiMap headers)
Sets the headers.
Parameters
headers the headers
Returns
this
Referenced by com.globo.galeb.handlers.RouterResponseHandler.handle().
ServerResponse com.globo.galeb.core.ServerResponse.setId (String id)
Sets the id.
Parameters
id the id
Returns
this
Referenced by com.globo.galeb.handlers.rest.GetMatcherHandler.handle().
ServerResponse com.globo.galeb.core.ServerResponse.setMessage (final String message)
Sets the message.
Parameters
message the message
Returns
this
Referenced by com.globo.galeb.core.ManagerService.endResponse(), com.globo.galeb.handlers.rest.PutMatcherHandler.handle(), com.globo.galeb.handlers.rest.PostMatcherHandler.handle(), com.globo.galeb.handlers.rest.DeleteMatcherHandler.handle(), and com.globo.galeb.handlers.rest.GetMatcherHandler.handle().
ServerResponse com.globo.galeb.core.ServerResponse.setStatusCode (Integer code)
Sets the status code.
Parameters
code the code
Returns
this
References com.globo.galeb.core.HttpCode.getMessage(), and com.globo.galeb.core.ServerResponse.setStatusCode().
Referenced by com.globo.galeb.core.ManagerService.endResponse(), com.globo.galeb.handlers.rest.DeleteMatcherHandler.handle(), com.globo.galeb.handlers.rest.PutMatcherHandler.handle(), com.globo.galeb.handlers.rest.PostMatcherHandler.handle(), com.globo.galeb.handlers.rest.GetMatcherHandler.handle(), com.globo.galeb.handlers.RouterResponseHandler.handle(), com.globo.galeb.core.ServerResponse.setStatusCode(), and com.globo.galeb.core.ServerResponse.showErrorAndClose().
void com.globo.galeb.core.ServerResponse.showErrorAndClose (final Throwable event)
Show error and finish connection (and close, if necessary).
Parameters
event the event/exception
References com.globo.galeb.core.ServerResponse.closeResponse(), com.globo.galeb.core.ServerResponse.endResponse(), com.globo.galeb.core.HttpCode.getMessage(), com.globo.galeb.core.HttpCode.INTERNAL_SERVER_ERROR, and com.globo.galeb.core.ServerResponse.setStatusCode().
Referenced by com.globo.galeb.handlers.RouterResponseHandler.handle(), com.globo.galeb.handlers.RouterRequestHandler.handle(), and com.globo.galeb.core.ServerResponse.ServerResponse().
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/core/ServerResponse.java