Galeb: com.globo.galeb.handlers.RouterRequestHandler Class Reference
com.globo.galeb.handlers.RouterRequestHandler Class Reference
Public Member Functions
void handle (final HttpServerRequest sRequest) throws RuntimeException
RouterRequestHandler (final Vertx vertx, final Farm farm, final ICounter counter, final IQueueService queueService, final Logger log)
boolean isHttpKeepAlive (MultiMap headers, HttpVersion httpVersion)
Protected Member Functions
void finalize () throws Throwable
Detailed Description
Class RouterRequestHandler.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Constructor & Destructor Documentation
com.globo.galeb.handlers.RouterRequestHandler.RouterRequestHandler (final Vertx vertx, final Farm farm, final ICounter counter, final IQueueService queueService, final Logger log)
Instantiates a new router request handler.
Parameters
vertx the vertx
farm the farm
counter the counter
queueService the queue service
log the logger
Member Function Documentation
void com.globo.galeb.handlers.RouterRequestHandler.finalize () throws Throwable protected
References com.globo.galeb.scheduler.IScheduler.cancel().
void com.globo.galeb.handlers.RouterRequestHandler.handle (final HttpServerRequest sRequest) throws RuntimeException
References com.globo.galeb.scheduler.IScheduler.cancel(), com.globo.galeb.scheduler.IScheduler.cancelHandler(), com.globo.galeb.core.Virtualhost.getChoice(), com.globo.galeb.core.Virtualhost.getRequestTimeOut(), com.globo.galeb.core.Farm.getVirtualhost(), com.globo.galeb.core.Virtualhost.hasAccessLog(), com.globo.galeb.core.Virtualhost.hasBackends(), com.globo.galeb.handlers.RouterRequestHandler.isHttpKeepAlive(), com.globo.galeb.core.ServerResponse.setChunked(), com.globo.galeb.core.Backend.setCounter(), com.globo.galeb.scheduler.IScheduler.setHandler(), com.globo.galeb.handlers.RouterResponseHandler.setHeaderHost(), com.globo.galeb.handlers.RouterResponseHandler.setInitialRequestTime(), com.globo.galeb.core.Backend.setKeepAlive(), com.globo.galeb.scheduler.impl.VertxDelayScheduler.setPeriod(), com.globo.galeb.core.Virtualhost.setQueue(), com.globo.galeb.core.ServerResponse.showErrorAndClose(), com.globo.galeb.streams.Pump.start(), and com.globo.galeb.core.Backend.toString().
boolean com.globo.galeb.handlers.RouterRequestHandler.isHttpKeepAlive (MultiMap headers, HttpVersion httpVersion)
Checks if is http keep alive.
Parameters
headers the headers
httpVersion the http version
Returns
true, if is http keep alive
Referenced by com.globo.galeb.handlers.RouterRequestHandler.handle().
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/handlers/RouterRequestHandler.java