Galeb: com.globo.galeb.metrics.StatsdClient Class Reference
com.globo.galeb.metrics.StatsdClient Class Reference
Classes
enum TypeStatsdMessage
Public Member Functions
StatsdClient (String statsDhost, Integer statsDPort, String prefix, final DatagramSocket socket, final Logger log)
StatsdClient (final DatagramSocket socket, final Logger log)
void send (final TypeStatsdMessage type, String message)
Detailed Description
Statsd Client Vert.X implementation
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Constructor & Destructor Documentation
com.globo.galeb.metrics.StatsdClient.StatsdClient (String statsDhost, Integer statsDPort, String prefix, final DatagramSocket socket, final Logger log)
Instantiates a new statsd client.
Parameters
statsDhost the stats dhost
statsDPort the stats d port
prefix the prefix
socket the socket
log the log
com.globo.galeb.metrics.StatsdClient.StatsdClient (final DatagramSocket socket, final Logger log)
Instantiates a new statsd client.
Parameters
socket the socket
log the log
Member Function Documentation
void com.globo.galeb.metrics.StatsdClient.send (final TypeStatsdMessage type, String message)
Send message to statsd
Parameters
type the type
message the message
References com.globo.galeb.metrics.StatsdClient.TypeStatsdMessage.getPattern().
Referenced by com.globo.galeb.metrics.CounterWithStatsd.decrHttpCode(), com.globo.galeb.metrics.CounterWithStatsd.httpCode(), com.globo.galeb.metrics.CounterWithStatsd.incrHttpCode(), com.globo.galeb.metrics.CounterWithStatsd.requestTime(), and com.globo.galeb.metrics.CounterWithStatsd.sendActiveSessions().
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/metrics/StatsdClient.java