Galeb: com.globo.galeb.handlers.ws.FrontendWebSocketHandler Class Reference
com.globo.galeb.handlers.ws.FrontendWebSocketHandler Class Reference
Public Member Functions
FrontendWebSocketHandler (final Vertx vertx, final Container container, final Farm farm)
void handle (final ServerWebSocket serverWebSocket)
Detailed Description
Class FrontendWebSocketHandler.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Constructor & Destructor Documentation
com.globo.galeb.handlers.ws.FrontendWebSocketHandler.FrontendWebSocketHandler (final Vertx vertx, final Container container, final Farm farm)
Instantiates a new frontend web socket handler.
Parameters
vertx the vertx
container the container
farm the farm
Member Function Documentation
void com.globo.galeb.handlers.ws.FrontendWebSocketHandler.handle (final ServerWebSocket serverWebSocket)
References com.globo.galeb.handlers.ws.BackendWebSocketHandler.closeWS(), com.globo.galeb.core.Backend.connect(), com.globo.galeb.handlers.ws.BackendWebSocketHandler.forwardToBackend(), com.globo.galeb.core.Virtualhost.getChoice(), com.globo.galeb.core.Farm.getVirtualhost(), com.globo.galeb.core.Virtualhost.hasBackends(), com.globo.galeb.core.Backend.setConnectionTimeout(), com.globo.galeb.core.Backend.setKeepAlive(), com.globo.galeb.core.Backend.setKeepAliveMaxRequest(), com.globo.galeb.core.Backend.setKeepAliveTimeOut(), com.globo.galeb.core.Backend.setMaxPoolSize(), and com.globo.galeb.core.Backend.toString().
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/handlers/ws/FrontendWebSocketHandler.java