Galeb: com.globo.galeb.handlers.rest.GetMatcherHandler Class Reference
com.globo.galeb.handlers.rest.GetMatcherHandler Class Reference
Public Member Functions
GetMatcherHandler (String id, final Logger log, final Farm farm)
void handle (HttpServerRequest req)
Detailed Description
Class GetMatcherHandler.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Constructor & Destructor Documentation
com.globo.galeb.handlers.rest.GetMatcherHandler.GetMatcherHandler (String id, final Logger log, final Farm farm)
Instantiates a new gets the matcher handler.
Parameters
id the id from uri
log the logger
farm the farm
Member Function Documentation
void com.globo.galeb.handlers.rest.GetMatcherHandler.handle (HttpServerRequest req)
References com.globo.galeb.core.HttpCode.BAD_REQUEST, com.globo.galeb.core.ManagerService.checkUriOk(), com.globo.galeb.core.ServerResponse.endResponse(), com.globo.galeb.core.Farm.getBackendJson(), com.globo.galeb.core.Farm.getFarmJson(), com.globo.galeb.core.HttpCode.getMessage(), com.globo.galeb.core.Farm.getVersion(), com.globo.galeb.core.Farm.getVirtualhostJson(), com.globo.galeb.core.HttpCode.NOT_FOUND, com.globo.galeb.core.HttpCode.OK, com.globo.galeb.core.Server.setHttpServerName(), com.globo.galeb.core.ServerResponse.setId(), com.globo.galeb.core.ServerResponse.setMessage(), com.globo.galeb.core.ManagerService.setRequest(), com.globo.galeb.core.ManagerService.setResponse(), and com.globo.galeb.core.ServerResponse.setStatusCode().
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/handlers/rest/GetMatcherHandler.java