Galeb: com.globo.galeb.core.Backend Class Reference
com.globo.galeb.core.Backend Class Reference
Classes
class CleanUpSessionHandler
Public Member Functions
String toString ()
boolean equals (Object obj)
int hashCode ()
Backend (final String backendId, final Vertx vertx)
Backend (JsonObject json, final Vertx vertx)
Backend setQueueService (IQueueService queueService)
String getHost ()
Integer getPort ()
Integer getConnectionTimeout ()
Backend setConnectionTimeout (Integer timeout)
Boolean isKeepalive ()
Backend setKeepAlive (boolean keepalive)
Long getKeepAliveMaxRequest ()
Backend setKeepAliveMaxRequest (Long maxRequestCount)
Long getKeepAliveTimeOut ()
Backend setKeepAliveTimeOut (Long keepAliveTimeOut)
Integer getMaxPoolSize ()
Backend setMaxPoolSize (Integer maxPoolSize)
Boolean isUsePooledBuffers ()
Integer getSendBufferSize ()
Integer getReceiveBufferSize ()
Boolean isPipelining ()
Backend setCounter (ICounter counter)
int getMinSessionPoolSize ()
void setMinSessionPoolSize (int minPoolSize)
HttpClient connect (RemoteUser remoteUser)
void close (RemoteUser remoteUser)
int getActiveConnections ()
boolean isClosed (RemoteUser remoteUser)
JsonObject toJson ()
void removeSession (RemoteUser remoteUser)
void registerConnectionsCounter ()
void unregisterConnectionsCounter ()
void publishConnection (int numConnections)
JsonObject makeConnectionInfoMessage (int numConnection)
void setRegistered (boolean registered)
boolean isRegistered ()
void callbackGlobalConnectionsInfo (JsonObject message)
Backend startSessionPool ()
Public Member Functions inherited from com.globo.galeb.core.Entity
JsonObject getProperties ()
Entity setStaticConf (String staticConf)
JsonObject toJson ()
Static Public Attributes
static final String KEEPALIVE_FIELDNAME = "keepalive"
static final String CONNECTION_TIMEOUT_FIELDNAME = "connectionTimeout"
static final String KEEPALIVE_MAXREQUEST_FIELDNAME = "keepaliveMaxRequest"
static final String KEEPALIVE_TIMEOUT_FIELDNAME = "keepAliveTimeOut"
static final String MAXPOOL_SIZE_FIELDNAME = "maxPoolSize"
static final String PIPELINING_FIELDNAME = "pipelining"
static final String RECEIVED_BUFFER_SIZE_FIELDNAME = "receiveBufferSize"
static final String SEND_BUFFER_SIZE_FIELDNAME = "sendBufferSize"
static final String USE_POOLED_BUFFERS_FIELDNAME = "usePooledBuffers"
static final String MIN_SESSION_POOL_SIZE_FIELDNAME = "minSessionPoolSize"
static final String ELEGIBLE_FIELDNAME = "_elegible"
static final String ACTIVE_CONNECTIONS_FIELDNAME = "_activeConnections"
static final String NUM_CONNECTIONS_FIELDNAME = "numConnections"
static final String UUID_FIELDNAME = "uuid"
Static Public Attributes inherited from com.globo.galeb.core.IJsonable
static final String ID_FIELDNAME = "id"
static final String PARENT_ID_FIELDNAME = "parentId"
static final String PROPERTIES_FIELDNAME = "properties"
static final String STATUS_FIELDNAME = "_status"
static final String CREATED_AT_FIELDNAME = "_created_at"
static final String MODIFIED_AT_FIELDNAME = "_modified_at"
static final String LINKS_FIELDNAME = "_links"
static final String LINKS_REL_FIELDNAME = "rel"
static final String LINKS_HREF_FIELDNAME = "href"
Protected Member Functions
void finalize () throws Throwable
Protected Member Functions inherited from com.globo.galeb.core.Entity
Entity prepareJson ()
Additional Inherited Members
Protected Attributes inherited from com.globo.galeb.core.Entity
JsonObject staticConf = new JsonObject()
String id = ""
final Long createdAt = System.currentTimeMillis()
Long modifiedAt = System.currentTimeMillis()
final JsonObject properties = new JsonObject()
final JsonObject idObj = new JsonObject()
String entityType = this.getClass().getSimpleName().toLowerCase()
Detailed Description
Class Backend.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Constructor & Destructor Documentation
com.globo.galeb.core.Backend.Backend (final String backendId, final Vertx vertx)
Instantiates a new backend.
Parameters
backendId the backend id
vertx the vertx
References com.globo.galeb.core.IJsonable.ID_FIELDNAME.
Referenced by com.globo.galeb.core.Backend.equals().
com.globo.galeb.core.Backend.Backend (JsonObject json, final Vertx vertx)
Instantiates a new backend.
Parameters
json the json
vertx the vertx
References com.globo.galeb.core.Entity.id, com.globo.galeb.core.IJsonable.ID_FIELDNAME, com.globo.galeb.core.IJsonable.PARENT_ID_FIELDNAME, com.globo.galeb.core.Entity.properties, com.globo.galeb.core.IJsonable.PROPERTIES_FIELDNAME, com.globo.galeb.core.Backend.publishConnection(), com.globo.galeb.core.bus.IQueueService.QUEUE_BACKEND_CONNECTIONS_PREFIX, and com.globo.galeb.core.Backend.registerConnectionsCounter().
Member Function Documentation
void com.globo.galeb.core.Backend.callbackGlobalConnectionsInfo (JsonObject body)
Callback global connections info.
Parameters
body the body
Implements com.globo.galeb.core.bus.ICallbackConnectionCounter.
void com.globo.galeb.core.Backend.close (RemoteUser remoteUser)
Close connection and destroy backendSession instance.
References com.globo.galeb.core.BackendSession.close().
Referenced by com.globo.galeb.handlers.RouterResponseHandler.handle().
HttpClient com.globo.galeb.core.Backend.connect (RemoteUser remoteUser)
Connect and gets HttpClient instance (through BackendSession).
Returns
the http client
References com.globo.galeb.core.BackendSession.connect(), com.globo.galeb.core.Backend.equals(), com.globo.galeb.core.Backend.getKeepAliveMaxRequest(), com.globo.galeb.core.Backend.getKeepAliveTimeOut(), com.globo.galeb.core.Backend.getMaxPoolSize(), com.globo.galeb.core.Entity.properties, com.globo.galeb.metrics.ICounter.sendActiveSessions(), com.globo.galeb.core.BackendSession.setBackendProperties(), com.globo.galeb.scheduler.IScheduler.setHandler(), com.globo.galeb.core.BackendSession.setKeepAliveMaxRequest(), com.globo.galeb.core.BackendSession.setKeepAliveTimeOut(), com.globo.galeb.core.BackendSession.setMaxPoolSize(), com.globo.galeb.scheduler.impl.VertxPeriodicScheduler.setPeriod(), com.globo.galeb.core.BackendSession.setQueueService(), com.globo.galeb.scheduler.IScheduler.start(), and com.globo.galeb.core.Backend.toString().
Referenced by com.globo.galeb.handlers.ws.FrontendWebSocketHandler.handle().
boolean com.globo.galeb.core.Backend.equals (Object obj)
References com.globo.galeb.core.Backend.Backend(), and com.globo.galeb.core.Entity.id.
Referenced by com.globo.galeb.core.Backend.connect().
void com.globo.galeb.core.Backend.finalize () throws Throwable protected
int com.globo.galeb.core.Backend.getActiveConnections ()
Gets the active connections.
Returns
the active connections
Referenced by com.globo.galeb.loadbalance.impl.LeastConnectionsFinder.add(), and com.globo.galeb.core.Backend.toJson().
Integer com.globo.galeb.core.Backend.getConnectionTimeout ()
Gets the connection timeout.
Returns
the connection timeout
String com.globo.galeb.core.Backend.getHost ()
Gets the host.
Returns
the host
Long com.globo.galeb.core.Backend.getKeepAliveMaxRequest ()
Gets the keep alive max request.
Returns
the keep alive max request
Referenced by com.globo.galeb.core.Backend.connect(), and com.globo.galeb.core.Backend.startSessionPool().
Long com.globo.galeb.core.Backend.getKeepAliveTimeOut ()
Gets the keep alive time out.
Returns
the keep alive time out
Referenced by com.globo.galeb.core.Backend.connect(), and com.globo.galeb.core.Backend.startSessionPool().
Integer com.globo.galeb.core.Backend.getMaxPoolSize ()
Gets the max pool size.
Returns
the max pool size
Referenced by com.globo.galeb.core.Backend.connect(), and com.globo.galeb.core.Backend.startSessionPool().
int com.globo.galeb.core.Backend.getMinSessionPoolSize ()
Gets the min session pool size.
Returns
the min session pool size
Integer com.globo.galeb.core.Backend.getPort ()
Gets the port.
Returns
the port
Integer com.globo.galeb.core.Backend.getReceiveBufferSize ()
Gets the receive buffer size.
Returns
the receive buffer size
Integer com.globo.galeb.core.Backend.getSendBufferSize ()
Gets the send buffer size.
Returns
the send buffer size
int com.globo.galeb.core.Backend.hashCode ()
References com.globo.galeb.core.Backend.toString().
boolean com.globo.galeb.core.Backend.isClosed (RemoteUser remoteUser)
Checks if is closed.
Returns
true, if is closed
Boolean com.globo.galeb.core.Backend.isKeepalive ()
Checks if is keepalive.
Returns
the boolean
Boolean com.globo.galeb.core.Backend.isPipelining ()
Checks if is pipelining.
Returns
the boolean
boolean com.globo.galeb.core.Backend.isRegistered ()
Checks if is registered.
Returns
true, if is registered
Implements com.globo.galeb.core.bus.ICallbackConnectionCounter.
Boolean com.globo.galeb.core.Backend.isUsePooledBuffers ()
Checks if is use pooled buffers.
Returns
the boolean
JsonObject com.globo.galeb.core.Backend.makeConnectionInfoMessage (int numConnection)
Make connection info message.
Parameters
numConnection the num connection
Returns
the json object
Referenced by com.globo.galeb.core.Backend.publishConnection().
void com.globo.galeb.core.Backend.publishConnection (int numConnections)
Publish zero to all instances.
References com.globo.galeb.core.Backend.makeConnectionInfoMessage(), and com.globo.galeb.core.bus.IQueueService.publishActiveConnections().
Referenced by com.globo.galeb.core.Backend.Backend(), and com.globo.galeb.core.Backend.unregisterConnectionsCounter().
void com.globo.galeb.core.Backend.registerConnectionsCounter ()
Register connections counter.
References com.globo.galeb.core.bus.IQueueService.registerConnectionsCounter().
Referenced by com.globo.galeb.core.Backend.Backend().
void com.globo.galeb.core.Backend.removeSession (RemoteUser remoteUser)
Removes the session.
Parameters
remoteUser the remote user
Referenced by com.globo.galeb.handlers.RouterResponseHandler.handle().
Backend com.globo.galeb.core.Backend.setConnectionTimeout (Integer timeout)
Sets the connection timeout.
Parameters
timeout the timeout
Returns
the backend
References com.globo.galeb.core.Entity.properties.
Referenced by com.globo.galeb.handlers.ws.FrontendWebSocketHandler.handle().
Backend com.globo.galeb.core.Backend.setCounter (ICounter counter)
Sets the counter.
Parameters
counter the counter
Returns
the backend
Referenced by com.globo.galeb.handlers.RouterRequestHandler.handle().
Backend com.globo.galeb.core.Backend.setKeepAlive (boolean keepalive)
Sets the keep alive.
Parameters
keepalive the keepalive
Returns
the backend
References com.globo.galeb.core.Entity.properties.
Referenced by com.globo.galeb.handlers.ws.FrontendWebSocketHandler.handle(), and com.globo.galeb.handlers.RouterRequestHandler.handle().
Backend com.globo.galeb.core.Backend.setKeepAliveMaxRequest (Long maxRequestCount)
Sets the keep alive max request.
Parameters
maxRequestCount the max request count
Returns
the backend
References com.globo.galeb.core.Entity.properties.
Referenced by com.globo.galeb.core.Virtualhost.addBackend(), and com.globo.galeb.handlers.ws.FrontendWebSocketHandler.handle().
Backend com.globo.galeb.core.Backend.setKeepAliveTimeOut (Long keepAliveTimeOut)
Sets the keep alive time out.
Parameters
keepAliveTimeOut the keep alive time out
Returns
the backend
References com.globo.galeb.core.Entity.properties.
Referenced by com.globo.galeb.core.Virtualhost.addBackend(), and com.globo.galeb.handlers.ws.FrontendWebSocketHandler.handle().
Backend com.globo.galeb.core.Backend.setMaxPoolSize (Integer maxPoolSize)
Sets the max pool size.
Parameters
maxPoolSize the max pool size
Returns
the backend
References com.globo.galeb.core.Entity.properties.
Referenced by com.globo.galeb.core.Virtualhost.addBackend(), and com.globo.galeb.handlers.ws.FrontendWebSocketHandler.handle().
void com.globo.galeb.core.Backend.setMinSessionPoolSize (int minPoolSize)
Sets the min session pool size.
Parameters
minPoolSize the new min session pool size
Referenced by com.globo.galeb.core.Virtualhost.addBackend().
Backend com.globo.galeb.core.Backend.setQueueService (IQueueService queueService)
Sets the queue service.
Parameters
queueService the queue service
Returns
the backend
Referenced by com.globo.galeb.core.Virtualhost.addBackend().
void com.globo.galeb.core.Backend.setRegistered (boolean registered)
Sets the registered.
Parameters
registered the new registered
Implements com.globo.galeb.core.bus.ICallbackConnectionCounter.
Backend com.globo.galeb.core.Backend.startSessionPool ()
Start session pool.
Returns
the backend
References com.globo.galeb.core.BackendSession.connect(), com.globo.galeb.core.Backend.getKeepAliveMaxRequest(), com.globo.galeb.core.Backend.getKeepAliveTimeOut(), com.globo.galeb.core.Backend.getMaxPoolSize(), com.globo.galeb.core.Entity.properties, com.globo.galeb.core.BackendSession.setBackendProperties(), com.globo.galeb.core.BackendSession.setKeepAliveMaxRequest(), com.globo.galeb.core.BackendSession.setKeepAliveTimeOut(), com.globo.galeb.core.BackendSession.setMaxPoolSize(), and com.globo.galeb.core.BackendSession.setQueueService().
Referenced by com.globo.galeb.core.Virtualhost.addBackend().
JsonObject com.globo.galeb.core.Backend.toJson ()
json representation of the Entity.
Returns
the json object
Implements com.globo.galeb.core.IJsonable.
References com.globo.galeb.core.Backend.getActiveConnections(), com.globo.galeb.core.Entity.idObj, com.globo.galeb.core.IJsonable.PARENT_ID_FIELDNAME, and com.globo.galeb.core.Entity.prepareJson().
String com.globo.galeb.core.Backend.toString ()
References com.globo.galeb.core.Entity.id.
Referenced by com.globo.galeb.core.Backend.connect(), com.globo.galeb.handlers.ws.FrontendWebSocketHandler.handle(), com.globo.galeb.handlers.RouterResponseHandler.handle(), com.globo.galeb.handlers.RouterRequestHandler.handle(), and com.globo.galeb.core.Backend.hashCode().
void com.globo.galeb.core.Backend.unregisterConnectionsCounter ()
Unregister connections counter.
References com.globo.galeb.core.Backend.publishConnection(), and com.globo.galeb.core.bus.IQueueService.unregisterConnectionsCounter().
Member Data Documentation
final String com.globo.galeb.core.Backend.ACTIVE_CONNECTIONS_FIELDNAME = "_activeConnections" static
The Constant ACTIVE_CONNECTIONS_FIELDNAME.
final String com.globo.galeb.core.Backend.CONNECTION_TIMEOUT_FIELDNAME = "connectionTimeout" static
The Constant CONNECTION_TIMEOUT_FIELDNAME.
final String com.globo.galeb.core.Backend.ELEGIBLE_FIELDNAME = "_elegible" static
The Constant ELEGIBLE_FIELDNAME.
Referenced by com.globo.galeb.core.bus.BackendMap.add(), com.globo.galeb.core.bus.BackendMap.del(), com.globo.galeb.verticles.HealthManagerVerticle.moveBackend(), com.globo.galeb.verticles.HealthManagerVerticle.postAddEvent(), and com.globo.galeb.verticles.HealthManagerVerticle.postDelEvent().
final String com.globo.galeb.core.Backend.KEEPALIVE_FIELDNAME = "keepalive" static
The Constant KEEPALIVE_FIELDNAME.
final String com.globo.galeb.core.Backend.KEEPALIVE_MAXREQUEST_FIELDNAME = "keepaliveMaxRequest" static
The Constant KEEPALIVE_MAXREQUEST_FIELDNAME.
Referenced by com.globo.galeb.core.Virtualhost.setStaticConf(), and com.globo.galeb.core.Virtualhost.toJson().
final String com.globo.galeb.core.Backend.KEEPALIVE_TIMEOUT_FIELDNAME = "keepAliveTimeOut" static
The Constant KEEPALIVE_TIMEOUT_FIELDNAME.
Referenced by com.globo.galeb.core.Virtualhost.setStaticConf(), and com.globo.galeb.core.Virtualhost.toJson().
final String com.globo.galeb.core.Backend.MAXPOOL_SIZE_FIELDNAME = "maxPoolSize" static
The Constant MAXPOOL_SIZE_FIELDNAME.
Referenced by com.globo.galeb.core.Virtualhost.setStaticConf(), and com.globo.galeb.core.Virtualhost.toJson().
final String com.globo.galeb.core.Backend.MIN_SESSION_POOL_SIZE_FIELDNAME = "minSessionPoolSize" static
The Constant MIN_SESSION_POOL_SIZE_FIELDNAME.
Referenced by com.globo.galeb.core.Virtualhost.setStaticConf(), and com.globo.galeb.core.Virtualhost.toJson().
final String com.globo.galeb.core.Backend.NUM_CONNECTIONS_FIELDNAME = "numConnections" static
The Constant NUM_CONNECTIONS_FIELDNAME.
final String com.globo.galeb.core.Backend.PIPELINING_FIELDNAME = "pipelining" static
The Constant PIPELINING_FIELDNAME.
final String com.globo.galeb.core.Backend.RECEIVED_BUFFER_SIZE_FIELDNAME = "receiveBufferSize" static
The Constant RECEIVED_BUFFER_SIZE_FIELDNAME.
final String com.globo.galeb.core.Backend.SEND_BUFFER_SIZE_FIELDNAME = "sendBufferSize" static
The Constant SEND_BUFFER_SIZE_FIELDNAME.
final String com.globo.galeb.core.Backend.USE_POOLED_BUFFERS_FIELDNAME = "usePooledBuffers" static
The Constant USE_POOLED_BUFFERS_FIELDNAME.
final String com.globo.galeb.core.Backend.UUID_FIELDNAME = "uuid" static
The Constant UUID_FIELDNAME.
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/core/Backend.java