Galeb: com.globo.galeb.handlers.rest.PutMatcherHandler Class Reference
com.globo.galeb.handlers.rest.PutMatcherHandler Class Reference
Public Member Functions
PutMatcherHandler (String id, final Logger log, final IQueueService queueService)
void handle (final HttpServerRequest req)
Detailed Description
Class PutMatcherHandler.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Constructor & Destructor Documentation
com.globo.galeb.handlers.rest.PutMatcherHandler.PutMatcherHandler (String id, final Logger log, final IQueueService queueService)
Instantiates a new put matcher handler.
Parameters
id the id from uri
log the logger
queueService the queue service
Member Function Documentation
void com.globo.galeb.handlers.rest.PutMatcherHandler.handle (final HttpServerRequest req)
References com.globo.galeb.core.HttpCode.ACCEPTED, com.globo.galeb.core.ManagerService.checkIdConsistency(), com.globo.galeb.core.ManagerService.checkIdPresent(), com.globo.galeb.core.ManagerService.checkMethodOk(), com.globo.galeb.core.ManagerService.checkUriOk(), com.globo.galeb.core.ServerResponse.endResponse(), com.globo.galeb.core.HttpCode.getMessage(), com.globo.galeb.core.HttpCode.OK, com.globo.galeb.core.bus.IQueueService.queueToChange(), com.globo.galeb.core.ServerResponse.setMessage(), com.globo.galeb.core.ManagerService.setRequest(), com.globo.galeb.core.ManagerService.setResponse(), com.globo.galeb.core.ServerResponse.setStatusCode(), and com.globo.galeb.core.ManagerService.statusFromMessageSchema().
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/handlers/rest/PutMatcherHandler.java