Galeb: com.globo.galeb.core.Farm Class Reference
com.globo.galeb.core.Farm Class Reference
Public Member Functions
Farm (final Verticle verticle, final IQueueService queueService)
Long getVersion ()
void setVersion (long version)
Vertx getVertx ()
Logger getLogger ()
String getVerticleId ()
Set< Backend > getBackends ()
Set< Virtualhost > getVirtualhosts ()
Virtualhost getVirtualhost (String key)
JsonObject toJson ()
Map< String, Virtualhost > getVirtualhostsToMap ()
boolean addToMap (String message)
boolean delFromMap (String message)
void registerQueueAction ()
void clearAll ()
void updateSharedData ()
String getFarmJson ()
String getVirtualhostJson (String id)
String getBackendJson (String id)
String collectionToJson (String key, Collection<?extends Entity > collection, String clazz)
Public Member Functions inherited from com.globo.galeb.core.Entity
JsonObject getProperties ()
Entity setStaticConf (String staticConf)
JsonObject toJson ()
Static Public Attributes
static final String FARM_MAP = "farm"
static final String FARM_BACKENDS_FIELDNAME = "backends"
static final String FARM_VIRTUALHOSTS_FIELDNAME = "virtualhosts"
static final String FARM_SHAREDDATA_ID = "farm.sharedData"
static final String FARM_VERSION_FIELDNAME = "version"
Static Public Attributes inherited from com.globo.galeb.core.IJsonable
static final String ID_FIELDNAME = "id"
static final String PARENT_ID_FIELDNAME = "parentId"
static final String PROPERTIES_FIELDNAME = "properties"
static final String STATUS_FIELDNAME = "_status"
static final String CREATED_AT_FIELDNAME = "_created_at"
static final String MODIFIED_AT_FIELDNAME = "_modified_at"
static final String LINKS_FIELDNAME = "_links"
static final String LINKS_REL_FIELDNAME = "rel"
static final String LINKS_HREF_FIELDNAME = "href"
Additional Inherited Members
Protected Member Functions inherited from com.globo.galeb.core.Entity
Entity prepareJson ()
Protected Attributes inherited from com.globo.galeb.core.Entity
JsonObject staticConf = new JsonObject()
String id = ""
final Long createdAt = System.currentTimeMillis()
Long modifiedAt = System.currentTimeMillis()
final JsonObject properties = new JsonObject()
final JsonObject idObj = new JsonObject()
String entityType = this.getClass().getSimpleName().toLowerCase()
Detailed Description
Class Farm.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Constructor & Destructor Documentation
com.globo.galeb.core.Farm.Farm (final Verticle verticle, final IQueueService queueService)
Instantiates a new farm.
Parameters
verticle the verticle
queueService the queue service
References com.globo.galeb.core.Entity.properties, com.globo.galeb.core.Farm.registerQueueAction(), and com.globo.galeb.core.Farm.toJson().
Member Function Documentation
boolean com.globo.galeb.core.Farm.addToMap (String body)
Adds to map.
Parameters
body the body
Returns
true, if successful
Implements com.globo.galeb.core.bus.ICallbackQueueAction.
References com.globo.galeb.core.Constants.CONF_ROOT_ROUTER, com.globo.galeb.core.Constants.CONF_STARTER_CONF, com.globo.galeb.core.Entity.properties, and com.globo.galeb.core.Entity.staticConf.
void com.globo.galeb.core.Farm.clearAll ()
Clear all virtualhosts.
Referenced by com.globo.galeb.core.bus.FarmMap.del().
String com.globo.galeb.core.Farm.collectionToJson (String key, Collection<?extends Entity > collection, String clazz)
Convert Collection to json.
Parameters
key the key
collection the collection
clazz the clazz
Returns
the string
Referenced by com.globo.galeb.core.Farm.updateSharedData().
boolean com.globo.galeb.core.Farm.delFromMap (String body)
Del from map.
Parameters
body the body
Returns
true, if successful
Implements com.globo.galeb.core.bus.ICallbackQueueAction.
String com.globo.galeb.core.Farm.getBackendJson (String id)
Gets the backend json by backendId.
Parameters
id the id
Returns
the backend json
References com.globo.galeb.core.bus.IQueueService.updateSharedData().
Referenced by com.globo.galeb.handlers.rest.GetMatcherHandler.handle().
Set<Backend> com.globo.galeb.core.Farm.getBackends ()
Gets the backends.
Returns
the backends
Referenced by com.globo.galeb.core.Farm.updateSharedData().
String com.globo.galeb.core.Farm.getFarmJson ()
Gets the farm json.
Returns
the farm json
References com.globo.galeb.core.bus.IQueueService.updateSharedData().
Referenced by com.globo.galeb.handlers.rest.GetMatcherHandler.handle().
Logger com.globo.galeb.core.Farm.getLogger ()
Gets the logger.
Returns
the logger
Long com.globo.galeb.core.Farm.getVersion ()
Gets the version.
Returns
the version
Referenced by com.globo.galeb.handlers.rest.GetMatcherHandler.handle().
String com.globo.galeb.core.Farm.getVerticleId ()
Gets the verticle id.
Returns
the verticle id
Vertx com.globo.galeb.core.Farm.getVertx ()
Gets the vertx.
Returns
the vertx
Virtualhost com.globo.galeb.core.Farm.getVirtualhost (String key)
Gets the virtualhost by virtualhostId (key).
Parameters
key the key
Returns
the virtualhost
Referenced by com.globo.galeb.handlers.ws.FrontendWebSocketHandler.handle(), com.globo.galeb.handlers.RouterRequestHandler.handle(), and com.globo.galeb.verticles.HealthManagerVerticle.moveBackend().
String com.globo.galeb.core.Farm.getVirtualhostJson (String id)
Gets the virtualhost json by virtualhostId.
Parameters
id the id
Returns
the virtualhost json
References com.globo.galeb.core.bus.IQueueService.updateSharedData().
Referenced by com.globo.galeb.handlers.rest.GetMatcherHandler.handle().
Set<Virtualhost> com.globo.galeb.core.Farm.getVirtualhosts ()
Gets the virtualhosts.
Returns
the virtualhosts
Map<String, Virtualhost> com.globo.galeb.core.Farm.getVirtualhostsToMap ()
Gets the virtualhosts (map).
Returns
the virtualhosts
Referenced by com.globo.galeb.core.bus.FarmMap.add().
void com.globo.galeb.core.Farm.registerQueueAction ()
Register queue action.
References com.globo.galeb.core.bus.IQueueService.registerQueueAdd(), com.globo.galeb.core.bus.IQueueService.registerQueueDel(), com.globo.galeb.core.bus.IQueueService.registerQueueVersion(), and com.globo.galeb.core.bus.IQueueService.registerUpdateSharedData().
Referenced by com.globo.galeb.core.Farm.Farm().
void com.globo.galeb.core.Farm.setVersion (long version)
Sets the version.
Parameters
version the version
Implements com.globo.galeb.core.bus.ICallbackQueueAction.
Referenced by com.globo.galeb.verticles.RouteManagerVerticle.setVersion().
JsonObject com.globo.galeb.core.Farm.toJson ()
json representation of the Entity.
Returns
the json object
Implements com.globo.galeb.core.IJsonable.
References com.globo.galeb.core.Entity.idObj, com.globo.galeb.core.Entity.prepareJson(), com.globo.galeb.core.IJsonable.STATUS_FIELDNAME, and com.globo.galeb.core.Virtualhost.toJson().
Referenced by com.globo.galeb.core.Farm.Farm(), and com.globo.galeb.core.Farm.updateSharedData().
void com.globo.galeb.core.Farm.updateSharedData ()
Update shared data.
Implements com.globo.galeb.core.bus.ICallbackSharedData.
References com.globo.galeb.core.Farm.collectionToJson(), com.globo.galeb.core.Farm.getBackends(), and com.globo.galeb.core.Farm.toJson().
Member Data Documentation
final String com.globo.galeb.core.Farm.FARM_BACKENDS_FIELDNAME = "backends" static
The Constant FARM_BACKENDS_FIELDNAME.
final String com.globo.galeb.core.Farm.FARM_MAP = "farm" static
The Constant FARM_MAP.
final String com.globo.galeb.core.Farm.FARM_SHAREDDATA_ID = "farm.sharedData" static
The Constant FARM_SHAREDDATA_ID.
final String com.globo.galeb.core.Farm.FARM_VERSION_FIELDNAME = "version" static
The Constant FARM_VERSION_FIELDNAME.
final String com.globo.galeb.core.Farm.FARM_VIRTUALHOSTS_FIELDNAME = "virtualhosts" static
The Constant FARM_VIRTUALHOSTS_FIELDNAME.
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/core/Farm.java