Galeb: com.globo.galeb.core.Entity Class Reference
com.globo.galeb.core.Entity Class Reference abstract
Public Member Functions
JsonObject getProperties ()
Entity setStaticConf (String staticConf)
JsonObject toJson ()
Protected Member Functions
Entity prepareJson ()
Protected Attributes
JsonObject staticConf = new JsonObject()
String id = ""
final Long createdAt = System.currentTimeMillis()
Long modifiedAt = System.currentTimeMillis()
final JsonObject properties = new JsonObject()
final JsonObject idObj = new JsonObject()
String entityType = this.getClass().getSimpleName().toLowerCase()
Additional Inherited Members
Static Public Attributes inherited from com.globo.galeb.core.IJsonable
static final String ID_FIELDNAME = "id"
static final String PARENT_ID_FIELDNAME = "parentId"
static final String PROPERTIES_FIELDNAME = "properties"
static final String STATUS_FIELDNAME = "_status"
static final String CREATED_AT_FIELDNAME = "_created_at"
static final String MODIFIED_AT_FIELDNAME = "_modified_at"
static final String LINKS_FIELDNAME = "_links"
static final String LINKS_REL_FIELDNAME = "rel"
static final String LINKS_HREF_FIELDNAME = "href"
Detailed Description
Class Entity.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Member Function Documentation
JsonObject com.globo.galeb.core.Entity.getProperties ()
Gets the properties.
Returns
the properties
References com.globo.galeb.core.Entity.properties.
Entity com.globo.galeb.core.Entity.prepareJson () protected
Prepare json.
Returns
this
References com.globo.galeb.core.IJsonable.CREATED_AT_FIELDNAME, com.globo.galeb.core.Entity.entityType, com.globo.galeb.core.Server.getHttpServerName(), com.globo.galeb.core.Entity.id, com.globo.galeb.core.IJsonable.ID_FIELDNAME, com.globo.galeb.core.IJsonable.LINKS_FIELDNAME, com.globo.galeb.core.IJsonable.LINKS_HREF_FIELDNAME, com.globo.galeb.core.IJsonable.LINKS_REL_FIELDNAME, com.globo.galeb.core.IJsonable.MODIFIED_AT_FIELDNAME, com.globo.galeb.core.IJsonable.PROPERTIES_FIELDNAME, and com.globo.galeb.core.IJsonable.STATUS_FIELDNAME.
Referenced by com.globo.galeb.core.Farm.toJson(), com.globo.galeb.core.Virtualhost.toJson(), and com.globo.galeb.core.Backend.toJson().
Entity com.globo.galeb.core.Entity.setStaticConf (String staticConf)
Sets the static conf.
Parameters
staticConf the static conf
Returns
this
JsonObject com.globo.galeb.core.Entity.toJson ()
json representation of the Entity.
Returns
the json object
Implements com.globo.galeb.core.IJsonable.
References com.globo.galeb.core.Entity.idObj.
Member Data Documentation
final Long com.globo.galeb.core.Entity.createdAt = System.currentTimeMillis() protected
The created at.
String com.globo.galeb.core.Entity.entityType = this.getClass().getSimpleName().toLowerCase() protected
The entity type.
Referenced by com.globo.galeb.core.Entity.prepareJson().
String com.globo.galeb.core.Entity.id = "" protected
The id.
Referenced by com.globo.galeb.core.Backend.Backend(), com.globo.galeb.core.Backend.equals(), com.globo.galeb.core.Virtualhost.getVirtualhostName(), com.globo.galeb.core.Entity.prepareJson(), and com.globo.galeb.core.Backend.toString().
final JsonObject com.globo.galeb.core.Entity.idObj = new JsonObject() protected
The id obj.
Referenced by com.globo.galeb.core.Virtualhost.setTransientState(), com.globo.galeb.core.Entity.toJson(), com.globo.galeb.core.Farm.toJson(), com.globo.galeb.core.Virtualhost.toJson(), and com.globo.galeb.core.Backend.toJson().
Long com.globo.galeb.core.Entity.modifiedAt = System.currentTimeMillis() protected
The modified at.
final JsonObject com.globo.galeb.core.Entity.properties = new JsonObject() protected
The properties.
Referenced by com.globo.galeb.core.Farm.addToMap(), com.globo.galeb.core.Backend.Backend(), com.globo.galeb.core.Backend.connect(), com.globo.galeb.core.Farm.Farm(), com.globo.galeb.core.Virtualhost.getChoice(), com.globo.galeb.core.Virtualhost.getLoadBalancePolicy(), com.globo.galeb.core.Entity.getProperties(), com.globo.galeb.core.Virtualhost.hasAccessLog(), com.globo.galeb.core.Virtualhost.isChunked(), com.globo.galeb.core.Backend.setConnectionTimeout(), com.globo.galeb.core.Backend.setKeepAlive(), com.globo.galeb.core.Backend.setKeepAliveMaxRequest(), com.globo.galeb.core.Backend.setKeepAliveTimeOut(), com.globo.galeb.core.Virtualhost.setLoadBalancePolicy(), com.globo.galeb.core.Backend.setMaxPoolSize(), com.globo.galeb.core.Backend.startSessionPool(), com.globo.galeb.core.Virtualhost.toJson(), and com.globo.galeb.core.Virtualhost.Virtualhost().
JsonObject com.globo.galeb.core.Entity.staticConf = new JsonObject() protected
The static conf.
Referenced by com.globo.galeb.core.Farm.addToMap().
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/core/Entity.java