Galeb: com.globo.galeb.loadbalance.impl.LeastConnectionsFinder Class Reference
com.globo.galeb.loadbalance.impl.LeastConnectionsFinder Class Reference
Public Member Functions
LeastConnectionsFinder (final Collection< Backend > backends)
void add (final Backend backend)
void addAll (final Collection< Backend > backends)
void update ()
void rebuild (final Collection< Backend > backends)
Backend get ()
Detailed Description
Class LeastConnectionsFinder: Find the backend with least connection
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Constructor & Destructor Documentation
com.globo.galeb.loadbalance.impl.LeastConnectionsFinder.LeastConnectionsFinder (final Collection< Backend > backends)
Instantiates a new least connections finder.
Parameters
backends the backends
Member Function Documentation
void com.globo.galeb.loadbalance.impl.LeastConnectionsFinder.add (final Backend backend)
Adds the backend to map.
Parameters
backend the backend
References com.globo.galeb.core.Backend.getActiveConnections().
Referenced by com.globo.galeb.loadbalance.impl.LeastConnectionsFinder.addAll().
void com.globo.galeb.loadbalance.impl.LeastConnectionsFinder.addAll (final Collection< Backend > backends)
Adds a backends collection to map.
Parameters
backends the backends
References com.globo.galeb.loadbalance.impl.LeastConnectionsFinder.add().
Referenced by com.globo.galeb.loadbalance.impl.LeastConnectionsFinder.rebuild(), and com.globo.galeb.loadbalance.impl.LeastConnectionsFinder.update().
Backend com.globo.galeb.loadbalance.impl.LeastConnectionsFinder.get ()
Gets the backend chosen
Returns
the backend
Referenced by com.globo.galeb.loadbalance.impl.LeastConnPolicy.getChoice().
void com.globo.galeb.loadbalance.impl.LeastConnectionsFinder.rebuild (final Collection< Backend > backends)
Rebuild the backends map
Parameters
backends the backends
References com.globo.galeb.loadbalance.impl.LeastConnectionsFinder.addAll().
Referenced by com.globo.galeb.loadbalance.impl.LeastConnPolicy.getChoice().
void com.globo.galeb.loadbalance.impl.LeastConnectionsFinder.update ()
Update the backends map
References com.globo.galeb.loadbalance.impl.LeastConnectionsFinder.addAll().
Referenced by com.globo.galeb.loadbalance.impl.LeastConnPolicy.getChoice().
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/loadbalance/impl/LeastConnectionsFinder.java