Galeb: com.globo.galeb.core.BackendSession Class Reference
com.globo.galeb.core.BackendSession Class Reference
Classes
class KeepAliveCheckLimitHandler
Public Member Functions
BackendSession (final Vertx vertx, String backendId)
BackendSession setKeepAliveMaxRequest (long keepAliveMaxRequest)
BackendSession setKeepAliveTimeOut (long keepAliveTimeOut)
boolean isKeepAliveLimit ()
BackendSession setBackendProperties (JsonObject backendProperties)
HttpClient connect ()
void close ()
boolean isClosed ()
BackendSession setQueueService (IQueueService queueService)
BackendSession setMaxPoolSize (int maxPoolSize)
Protected Member Functions
void finalize () throws Throwable
Detailed Description
Class BackendSession.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Constructor & Destructor Documentation
com.globo.galeb.core.BackendSession.BackendSession (final Vertx vertx, String backendId)
Instantiates a new backend session.
Parameters
vertx the vertx
backendId the backend id
Member Function Documentation
void com.globo.galeb.core.BackendSession.close ()
Close connection and destroy http client instance.
References com.globo.galeb.scheduler.IScheduler.cancel().
Referenced by com.globo.galeb.core.Backend.close(), and com.globo.galeb.core.BackendSession.connect().
HttpClient com.globo.galeb.core.BackendSession.connect ()
Connect and gets http client instance.
Returns
the http client
References com.globo.galeb.core.BackendSession.close(), com.globo.galeb.core.BackendSession.isClosed(), com.globo.galeb.core.BackendSession.isKeepAliveLimit(), com.globo.galeb.core.bus.IQueueService.publishBackendFail(), com.globo.galeb.scheduler.impl.VertxPeriodicScheduler.setHandler(), com.globo.galeb.scheduler.IScheduler.setPeriod(), and com.globo.galeb.scheduler.IScheduler.start().
Referenced by com.globo.galeb.core.Backend.connect(), and com.globo.galeb.core.Backend.startSessionPool().
void com.globo.galeb.core.BackendSession.finalize () throws Throwable protected
References com.globo.galeb.scheduler.IScheduler.cancel().
boolean com.globo.galeb.core.BackendSession.isClosed ()
Checks if is closed.
Returns
true, if is closed
Referenced by com.globo.galeb.core.BackendSession.connect().
boolean com.globo.galeb.core.BackendSession.isKeepAliveLimit ()
Checks if is keep alive limit.
Returns
true, if is keep alive limit
Referenced by com.globo.galeb.core.BackendSession.connect().
BackendSession com.globo.galeb.core.BackendSession.setBackendProperties (JsonObject backendProperties)
Sets the backend properties.
Parameters
backendProperties the backend properties
Returns
the backend session
Referenced by com.globo.galeb.core.Backend.connect(), and com.globo.galeb.core.Backend.startSessionPool().
BackendSession com.globo.galeb.core.BackendSession.setKeepAliveMaxRequest (long keepAliveMaxRequest)
Sets the keep alive max request.
Parameters
keepAliveMaxRequest the keep alive max request
Returns
the backend session
Referenced by com.globo.galeb.core.Backend.connect(), and com.globo.galeb.core.Backend.startSessionPool().
BackendSession com.globo.galeb.core.BackendSession.setKeepAliveTimeOut (long keepAliveTimeOut)
Sets the keep alive time out.
Parameters
keepAliveTimeOut the keep alive time out
Returns
the backend session
Referenced by com.globo.galeb.core.Backend.connect(), and com.globo.galeb.core.Backend.startSessionPool().
BackendSession com.globo.galeb.core.BackendSession.setMaxPoolSize (int maxPoolSize)
Sets the max pool size.
Parameters
maxPoolSize the new max pool size
Returns
this
Referenced by com.globo.galeb.core.Backend.connect(), and com.globo.galeb.core.Backend.startSessionPool().
BackendSession com.globo.galeb.core.BackendSession.setQueueService (IQueueService queueService)
Sets the queue service.
Parameters
queueService the new queue service
Returns
this
Referenced by com.globo.galeb.core.Backend.connect(), and com.globo.galeb.core.Backend.startSessionPool().
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/core/BackendSession.java