Galeb: com.globo.galeb.core.bus.FarmMap Class Reference
com.globo.galeb.core.bus.FarmMap Class Reference
Public Member Functions
FarmMap ()
boolean add ()
boolean del ()
boolean reset ()
boolean change ()
Public Member Functions inherited from com.globo.galeb.core.bus.MessageToMap< T >
MessageToMap< T > setVerticleId (String id)
MessageToMap< T > setLogger (final Logger log)
MessageToMap< T > setMessageBus (final MessageBus messageBus)
MessageToMap< T > setMap (final Map< String, T > map)
MessageToMap< T > setVertx (final Vertx vertx)
boolean add ()
boolean del ()
boolean reset ()
boolean change ()
MessageToMap< T > staticConf (String jsonConf)
Additional Inherited Members
Protected Attributes inherited from com.globo.galeb.core.bus.MessageToMap< T >
String uriBase = ""
JsonObject entity = new JsonObject()
String entityId = ""
String parentId = ""
Map< String, T > map = new HashMap<>()
MessageBus messageBus = new MessageBus().setUri("/null")
Logger log = null
String verticleId = ""
Vertx vertx = null
String staticConf = ""
Detailed Description
Class FarmMap.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Constructor & Destructor Documentation
com.globo.galeb.core.bus.FarmMap.FarmMap ()
Instantiates a new farm map.
Member Function Documentation
boolean com.globo.galeb.core.bus.FarmMap.add ()
References com.globo.galeb.core.bus.VirtualhostMap.add(), com.globo.galeb.core.bus.BackendMap.add(), com.globo.galeb.core.Virtualhost.BACKENDS_ELIGIBLE_FIELDNAME, com.globo.galeb.core.Virtualhost.BACKENDS_FIELDNAME, com.globo.galeb.core.bus.MessageToMap< T >.entity, com.globo.galeb.core.Farm.getVirtualhostsToMap(), com.globo.galeb.core.IJsonable.ID_FIELDNAME, com.globo.galeb.core.bus.MessageToMap< T >.log, com.globo.galeb.core.bus.MessageBus.make(), com.globo.galeb.core.bus.MessageToMap< T >.map, com.globo.galeb.core.bus.MessageBus.setEntity(), com.globo.galeb.core.bus.MessageToMap< T >.setLogger(), com.globo.galeb.core.bus.MessageToMap< T >.setMap(), com.globo.galeb.core.bus.MessageToMap< T >.setMessageBus(), com.globo.galeb.core.bus.MessageToMap< T >.setVerticleId(), com.globo.galeb.core.bus.MessageToMap< T >.setVertx(), com.globo.galeb.core.bus.MessageToMap< T >.staticConf, com.globo.galeb.core.bus.MessageToMap< T >.verticleId, and com.globo.galeb.core.bus.MessageToMap< T >.vertx.
boolean com.globo.galeb.core.bus.FarmMap.change ()
boolean com.globo.galeb.core.bus.FarmMap.del ()
References com.globo.galeb.core.Farm.clearAll(), and com.globo.galeb.core.bus.MessageToMap< T >.map.
boolean com.globo.galeb.core.bus.FarmMap.reset ()
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/core/bus/FarmMap.java