Galeb: com.globo.galeb.core.HttpCode Class Reference
com.globo.galeb.core.HttpCode Class Reference
Static Public Member Functions
static String getMessage (int statusCode)
static String getMessage (int statusCode, boolean asJson)
static int codeFamily (int code)
static boolean isServerError (int code)
Static Public Attributes
static final int OK = HttpResponseStatus.OK.code()
static final int ACCEPTED = HttpResponseStatus.ACCEPTED.code()
static final int FOUND = HttpResponseStatus.FOUND.code()
static final int TEMPORARY_REDIRECT = HttpResponseStatus.TEMPORARY_REDIRECT.code()
static final int BAD_REQUEST = HttpResponseStatus.BAD_REQUEST.code()
static final int NOT_FOUND = HttpResponseStatus.NOT_FOUND.code()
static final int METHOD_NOT_ALLOWED = HttpResponseStatus.METHOD_NOT_ALLOWED.code()
static final int INTERNAL_SERVER_ERROR = HttpResponseStatus.INTERNAL_SERVER_ERROR.code()
static final int BAD_GATEWAY = HttpResponseStatus.BAD_GATEWAY.code()
static final int SERVICE_UNAVAILABLE = HttpResponseStatus.SERVICE_UNAVAILABLE.code()
static final int GATEWAY_TIMEOUT = HttpResponseStatus.GATEWAY_TIMEOUT.code()
Detailed Description
Class HttpCode.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Member Function Documentation
static int com.globo.galeb.core.HttpCode.codeFamily (int code) static
Code family.
Parameters
code the code
Returns
the int
Referenced by com.globo.galeb.core.HttpCode.isServerError().
static String com.globo.galeb.core.HttpCode.getMessage (int statusCode) static
Gets the message.
Parameters
statusCode the status code
Returns
the message
Referenced by com.globo.galeb.core.ManagerService.endResponse(), com.globo.galeb.handlers.rest.PutMatcherHandler.handle(), com.globo.galeb.handlers.rest.DeleteMatcherHandler.handle(), com.globo.galeb.handlers.rest.PostMatcherHandler.handle(), com.globo.galeb.handlers.rest.GetMatcherHandler.handle(), com.globo.galeb.core.ServerResponse.setStatusCode(), and com.globo.galeb.core.ServerResponse.showErrorAndClose().
static String com.globo.galeb.core.HttpCode.getMessage (int statusCode, boolean asJson) static
Gets the message.
Parameters
statusCode the status code
asJson the as json
Returns
the message
static boolean com.globo.galeb.core.HttpCode.isServerError (int code) static
Checks if is server error.
Parameters
code the code
Returns
true, if is server error
References com.globo.galeb.core.HttpCode.codeFamily().
Referenced by com.globo.galeb.core.ServerResponse.logRequest().
Member Data Documentation
final int com.globo.galeb.core.HttpCode.ACCEPTED = HttpResponseStatus.ACCEPTED.code() static
The Constant ACCEPTED.
Referenced by com.globo.galeb.handlers.rest.DeleteMatcherHandler.handle(), and com.globo.galeb.handlers.rest.PutMatcherHandler.handle().
final int com.globo.galeb.core.HttpCode.BAD_GATEWAY = HttpResponseStatus.BAD_GATEWAY.code() static
The Constant BAD_GATEWAY.
Referenced by com.globo.galeb.exceptions.BadGatewayException.BadGatewayException().
final int com.globo.galeb.core.HttpCode.BAD_REQUEST = HttpResponseStatus.BAD_REQUEST.code() static
The Constant BAD_REQUEST.
Referenced by com.globo.galeb.exceptions.BadRequestException.BadRequestException(), com.globo.galeb.core.ManagerService.checkIdConsistency(), com.globo.galeb.core.ManagerService.checkIdPresent(), com.globo.galeb.core.ManagerService.endResponse(), com.globo.galeb.handlers.rest.GetMatcherHandler.handle(), and com.globo.galeb.core.ManagerService.statusFromMessageSchema().
final int com.globo.galeb.core.HttpCode.FOUND = HttpResponseStatus.FOUND.code() static
The Constant FOUND.
final int com.globo.galeb.core.HttpCode.GATEWAY_TIMEOUT = HttpResponseStatus.GATEWAY_TIMEOUT.code() static
The Constant GATEWAY_TIMEOUT.
Referenced by com.globo.galeb.exceptions.GatewayTimeoutException.GatewayTimeoutException().
final int com.globo.galeb.core.HttpCode.INTERNAL_SERVER_ERROR = HttpResponseStatus.INTERNAL_SERVER_ERROR.code() static
The Constant INTERNAL_SERVER_ERROR.
Referenced by com.globo.galeb.core.ServerResponse.sendRequestCount(), and com.globo.galeb.core.ServerResponse.showErrorAndClose().
final int com.globo.galeb.core.HttpCode.METHOD_NOT_ALLOWED = HttpResponseStatus.METHOD_NOT_ALLOWED.code() static
The Constant METHOD_NOT_ALLOWED.
Referenced by com.globo.galeb.core.ManagerService.checkMethodOk().
final int com.globo.galeb.core.HttpCode.NOT_FOUND = HttpResponseStatus.NOT_FOUND.code() static
The Constant NOT_FOUND.
Referenced by com.globo.galeb.core.ManagerService.checkUriOk(), com.globo.galeb.handlers.rest.GetMatcherHandler.handle(), and com.globo.galeb.exceptions.NotFoundException.NotFoundException().
final int com.globo.galeb.core.HttpCode.OK = HttpResponseStatus.OK.code() static
The Constant OK.
Referenced by com.globo.galeb.handlers.rest.DeleteMatcherHandler.handle(), com.globo.galeb.handlers.rest.PutMatcherHandler.handle(), com.globo.galeb.handlers.rest.PostMatcherHandler.handle(), com.globo.galeb.handlers.rest.GetMatcherHandler.handle(), and com.globo.galeb.core.ManagerService.statusFromMessageSchema().
final int com.globo.galeb.core.HttpCode.SERVICE_UNAVAILABLE = HttpResponseStatus.SERVICE_UNAVAILABLE.code() static
The Constant SERVICE_UNAVAILABLE.
Referenced by com.globo.galeb.exceptions.ServiceUnavailableException.ServiceUnavailableException().
final int com.globo.galeb.core.HttpCode.TEMPORARY_REDIRECT = HttpResponseStatus.TEMPORARY_REDIRECT.code() static
The Constant TEMPORARY_REDIRECT.
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/core/HttpCode.java