Galeb: com.globo.galeb.core.bus.BackendMap Class Reference
com.globo.galeb.core.bus.BackendMap Class Reference
Public Member Functions
BackendMap ()
boolean add ()
boolean del ()
boolean reset ()
boolean change ()
Public Member Functions inherited from com.globo.galeb.core.bus.MessageToMap< T >
MessageToMap< T > setVerticleId (String id)
MessageToMap< T > setLogger (final Logger log)
MessageToMap< T > setMessageBus (final MessageBus messageBus)
MessageToMap< T > setMap (final Map< String, T > map)
MessageToMap< T > setVertx (final Vertx vertx)
boolean add ()
boolean del ()
boolean reset ()
boolean change ()
MessageToMap< T > staticConf (String jsonConf)
Additional Inherited Members
Protected Attributes inherited from com.globo.galeb.core.bus.MessageToMap< T >
String uriBase = ""
JsonObject entity = new JsonObject()
String entityId = ""
String parentId = ""
Map< String, T > map = new HashMap<>()
MessageBus messageBus = new MessageBus().setUri("/null")
Logger log = null
String verticleId = ""
Vertx vertx = null
String staticConf = ""
Detailed Description
Class BackendMap.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Constructor & Destructor Documentation
com.globo.galeb.core.bus.BackendMap.BackendMap ()
Instantiates a new backend map.
Member Function Documentation
boolean com.globo.galeb.core.bus.BackendMap.add ()
References com.globo.galeb.core.Virtualhost.addBackend(), com.globo.galeb.core.Backend.ELEGIBLE_FIELDNAME, com.globo.galeb.core.bus.MessageToMap< T >.entity, com.globo.galeb.core.bus.MessageToMap< T >.entityId, com.globo.galeb.core.bus.MessageToMap< T >.log, com.globo.galeb.core.bus.MessageToMap< T >.map, com.globo.galeb.core.bus.MessageToMap< T >.parentId, and com.globo.galeb.core.bus.MessageToMap< T >.verticleId.
Referenced by com.globo.galeb.core.bus.FarmMap.add().
boolean com.globo.galeb.core.bus.BackendMap.change ()
boolean com.globo.galeb.core.bus.BackendMap.del ()
References com.globo.galeb.core.Backend.ELEGIBLE_FIELDNAME, com.globo.galeb.core.bus.MessageToMap< T >.entity, com.globo.galeb.core.bus.MessageToMap< T >.entityId, com.globo.galeb.core.bus.MessageBus.getUri(), com.globo.galeb.core.bus.MessageBus.getUriBase(), com.globo.galeb.core.bus.MessageToMap< T >.log, com.globo.galeb.core.bus.MessageToMap< T >.map, com.globo.galeb.core.bus.MessageToMap< T >.messageBus, com.globo.galeb.core.bus.MessageToMap< T >.parentId, com.globo.galeb.core.Virtualhost.removeBackend(), and com.globo.galeb.core.bus.MessageToMap< T >.verticleId.
boolean com.globo.galeb.core.bus.BackendMap.reset ()
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/core/bus/BackendMap.java