Galeb: com.globo.galeb.verticles.HealthManagerVerticle Class Reference
com.globo.galeb.verticles.HealthManagerVerticle Class Reference
Public Member Functions
void start ()
void setVersion (Long version)
void postAddEvent (String message)
void postDelEvent (String message)
void moveBackend (String backend, boolean elegible) throws UnsupportedEncodingException
Detailed Description
Class HealthManagerVerticle.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Member Function Documentation
void com.globo.galeb.verticles.HealthManagerVerticle.moveBackend (String backend, boolean status) throws UnsupportedEncodingException
Move backend.
Parameters
backend the backend
status the status
Exceptions
UnsupportedEncodingException the unsupported encoding exception
Implements com.globo.galeb.core.bus.ICallbackHealthcheck.
References com.globo.galeb.core.Backend.ELEGIBLE_FIELDNAME, com.globo.galeb.core.Virtualhost.getBackends(), com.globo.galeb.core.Farm.getVirtualhost(), com.globo.galeb.core.bus.IQueueService.queueToAdd(), com.globo.galeb.core.bus.IQueueService.queueToDel(), and com.globo.galeb.core.Virtualhost.toJson().
void com.globo.galeb.verticles.HealthManagerVerticle.postAddEvent (String message)
This method is called when information about an Add event which was previously requested using an asynchronous interface becomes available.
Parameters
message the message
Implements com.globo.galeb.core.bus.IEventObserver.
References com.globo.galeb.core.Backend.ELEGIBLE_FIELDNAME, com.globo.galeb.core.bus.MessageBus.getEntity(), com.globo.galeb.core.bus.MessageBus.getEntityId(), com.globo.galeb.core.bus.MessageBus.getParentId(), and com.globo.galeb.core.bus.MessageBus.getUriBase().
void com.globo.galeb.verticles.HealthManagerVerticle.postDelEvent (String message)
This method is called when information about an Del event which was previously requested using an asynchronous interface becomes available.
Parameters
message the message
Implements com.globo.galeb.core.bus.IEventObserver.
References com.globo.galeb.core.Backend.ELEGIBLE_FIELDNAME, com.globo.galeb.core.bus.MessageBus.getEntity(), com.globo.galeb.core.bus.MessageBus.getEntityId(), com.globo.galeb.core.bus.MessageBus.getParentId(), and com.globo.galeb.core.bus.MessageBus.getUriBase().
void com.globo.galeb.verticles.HealthManagerVerticle.setVersion (Long version)
This method is called when information about an Version event which was previously requested using an asynchronous interface becomes available.
Parameters
version the version
Implements com.globo.galeb.core.bus.IEventObserver.
void com.globo.galeb.verticles.HealthManagerVerticle.start ()
References com.globo.galeb.core.bus.IQueueService.registerHealthcheck(), com.globo.galeb.scheduler.IScheduler.setHandler(), com.globo.galeb.scheduler.impl.VertxPeriodicScheduler.setPeriod(), and com.globo.galeb.scheduler.IScheduler.start().
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/verticles/HealthManagerVerticle.java