Galeb: com.globo.galeb.core.bus.MessageBus Class Reference
com.globo.galeb.core.bus.MessageBus Class Reference
Public Member Functions
MessageBus ()
MessageBus (String message)
String getParentId ()
MessageBus setParentId (String parentId)
JsonObject getEntity ()
String getEntityId ()
MessageBus setEntity (String entityStr)
MessageBus setEntity (JsonObject entityJson)
String getUri ()
MessageBus setUri (String uriStr)
String getUriBase ()
MessageBus make ()
String toString ()
JsonObject toJson ()
Static Public Attributes
static final String ENTITY_FIELDNAME = "entity"
static final String PARENT_ID_FIELDNAME = "parentId"
static final String URI_FIELDNAME = "uri"
Detailed Description
Class MessageBus.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Constructor & Destructor Documentation
com.globo.galeb.core.bus.MessageBus.MessageBus ()
Instantiates a new message bus.
com.globo.galeb.core.bus.MessageBus.MessageBus (String message)
Instantiates a new message bus.
Parameters
message the message
References com.globo.galeb.core.bus.MessageBus.make(), com.globo.galeb.core.bus.MessageBus.setEntity(), com.globo.galeb.core.bus.MessageBus.setParentId(), and com.globo.galeb.core.bus.MessageBus.setUri().
Member Function Documentation
JsonObject com.globo.galeb.core.bus.MessageBus.getEntity ()
Gets the entity.
Returns
the entity
Referenced by com.globo.galeb.core.bus.MessageBus.getEntityId(), com.globo.galeb.core.bus.MessageBus.make(), com.globo.galeb.verticles.HealthManagerVerticle.postAddEvent(), com.globo.galeb.verticles.HealthManagerVerticle.postDelEvent(), and com.globo.galeb.core.bus.MessageToMap< T >.setMessageBus().
String com.globo.galeb.core.bus.MessageBus.getEntityId ()
Gets the entity id.
Returns
the entity id
References com.globo.galeb.core.bus.MessageBus.getEntity(), and com.globo.galeb.core.IJsonable.ID_FIELDNAME.
Referenced by com.globo.galeb.verticles.HealthManagerVerticle.postAddEvent(), com.globo.galeb.verticles.HealthManagerVerticle.postDelEvent(), and com.globo.galeb.core.bus.MessageToMap< T >.setMessageBus().
String com.globo.galeb.core.bus.MessageBus.getParentId ()
Gets the parent id.
Returns
the parent id
Referenced by com.globo.galeb.verticles.HealthManagerVerticle.postAddEvent(), com.globo.galeb.verticles.HealthManagerVerticle.postDelEvent(), and com.globo.galeb.core.bus.MessageToMap< T >.setMessageBus().
String com.globo.galeb.core.bus.MessageBus.getUri ()
Gets the uri.
Returns
the uri
Referenced by com.globo.galeb.core.bus.VirtualhostMap.del(), and com.globo.galeb.core.bus.BackendMap.del().
String com.globo.galeb.core.bus.MessageBus.getUriBase ()
Gets the uri base.
Returns
the uri base
Referenced by com.globo.galeb.core.bus.VirtualhostMap.del(), com.globo.galeb.core.bus.BackendMap.del(), com.globo.galeb.verticles.HealthManagerVerticle.postAddEvent(), com.globo.galeb.verticles.HealthManagerVerticle.postDelEvent(), and com.globo.galeb.core.bus.MessageToMap< T >.setMessageBus().
MessageBus com.globo.galeb.core.bus.MessageBus.make ()
Make messageBus message.
Returns
this
References com.globo.galeb.core.bus.MessageBus.getEntity().
Referenced by com.globo.galeb.core.bus.FarmMap.add(), and com.globo.galeb.core.bus.MessageBus.MessageBus().
MessageBus com.globo.galeb.core.bus.MessageBus.setEntity (String entityStr)
Sets the entity.
Parameters
entityStr the entity str
Returns
this
Referenced by com.globo.galeb.core.bus.FarmMap.add(), and com.globo.galeb.core.bus.MessageBus.MessageBus().
MessageBus com.globo.galeb.core.bus.MessageBus.setEntity (JsonObject entityJson)
Sets the entity.
Parameters
entityJson the entity json
Returns
this
MessageBus com.globo.galeb.core.bus.MessageBus.setParentId (String parentId)
Sets the parent id.
Parameters
parentId the parent id
Returns
this
Referenced by com.globo.galeb.core.bus.MessageBus.MessageBus().
MessageBus com.globo.galeb.core.bus.MessageBus.setUri (String uriStr)
Sets the uri.
Parameters
uriStr the uri str
Returns
this
Referenced by com.globo.galeb.core.bus.MessageBus.MessageBus().
JsonObject com.globo.galeb.core.bus.MessageBus.toJson ()
Json representation of the messageBus.
Returns
the safe json object
String com.globo.galeb.core.bus.MessageBus.toString ()
Member Data Documentation
final String com.globo.galeb.core.bus.MessageBus.ENTITY_FIELDNAME = "entity" static
The Constant ENTITY_FIELDNAME.
final String com.globo.galeb.core.bus.MessageBus.PARENT_ID_FIELDNAME = "parentId" static
The Constant PARENT_ID_FIELDNAME.
final String com.globo.galeb.core.bus.MessageBus.URI_FIELDNAME = "uri" static
The Constant URI_FIELDNAME.
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/core/bus/MessageBus.java