Galeb: com.globo.galeb.core.RequestData Class Reference
com.globo.galeb.core.RequestData Class Reference
Public Member Functions
RequestData ()
RequestData (final String remoteAddress, final String remotePort)
RequestData (final MultiMap headers, final MultiMap params, final URI uri, final String remoteAddress, final String remotePort)
RequestData (final HttpServerRequest request)
RequestData (final ServerWebSocket request)
MultiMap getHeaders ()
MultiMap getParams ()
URI getUri ()
String getRemoteAddress ()
String getRemotePort ()
String getHeaderHost ()
JsonObject getProperties ()
void setProperties (final JsonObject properties)
Detailed Description
Class RequestData.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Constructor & Destructor Documentation
com.globo.galeb.core.RequestData.RequestData ()
Instantiates a new request data.
com.globo.galeb.core.RequestData.RequestData (final String remoteAddress, final String remotePort)
Instantiates a new request data.
Parameters
remoteAddress the remote address
remotePort the remote port
com.globo.galeb.core.RequestData.RequestData (final MultiMap headers, final MultiMap params, final URI uri, final String remoteAddress, final String remotePort)
Instantiates a new request data.
Parameters
headers the headers
params the params
uri the uri
remoteAddress the remote address
remotePort the remote port
com.globo.galeb.core.RequestData.RequestData (final HttpServerRequest request)
Instantiates a new request data.
Parameters
request the httpServerRequest
com.globo.galeb.core.RequestData.RequestData (final ServerWebSocket request)
Instantiates a new request data.
Parameters
request the request
Member Function Documentation
String com.globo.galeb.core.RequestData.getHeaderHost ()
Gets the header host.
Returns
the header host
MultiMap com.globo.galeb.core.RequestData.getHeaders ()
Gets the headers.
Returns
the headers
MultiMap com.globo.galeb.core.RequestData.getParams ()
Gets the params.
Returns
the params
JsonObject com.globo.galeb.core.RequestData.getProperties ()
Gets the properties.
Returns
the properties
Referenced by com.globo.galeb.loadbalance.impl.LeastConnPolicy.getChoice(), and com.globo.galeb.loadbalance.impl.HashPolicy.getChoice().
String com.globo.galeb.core.RequestData.getRemoteAddress ()
Gets the remote address.
Returns
the remote address
Referenced by com.globo.galeb.loadbalance.impl.HashPolicy.getChoice().
String com.globo.galeb.core.RequestData.getRemotePort ()
Gets the remote port.
Returns
the remote port
URI com.globo.galeb.core.RequestData.getUri ()
Gets the uri.
Returns
the uri
void com.globo.galeb.core.RequestData.setProperties (final JsonObject properties)
Sets the properties.
Parameters
properties the new properties
Referenced by com.globo.galeb.core.Virtualhost.getChoice().
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/core/RequestData.java