Galeb: com.globo.galeb.core.Server Class Reference
com.globo.galeb.core.Server Class Reference
Public Member Functions
Server (final Vertx vertx, final Container container, final ICounter counter)
Server start (final Object caller)
Server setHttpServerRequestHandler (final Handler< HttpServerRequest > httpServerRequestHandler)
Server setWebsocketServerRequestHandler (final Handler< ServerWebSocket > websocketServerRequestHandler)
Server setDefaultPort (Integer defaultPort)
Static Public Member Functions
static String getHttpServerName ()
static void setHttpServerName (String httpServerName)
Detailed Description
Class Server.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Constructor & Destructor Documentation
com.globo.galeb.core.Server.Server (final Vertx vertx, final Container container, final ICounter counter)
Instantiates a new server.
Parameters
vertx the vertx
container the container
counter the counter
Member Function Documentation
static String com.globo.galeb.core.Server.getHttpServerName () static
Gets the http server name.
Returns
the http server name
Referenced by com.globo.galeb.core.Entity.prepareJson().
Server com.globo.galeb.core.Server.setDefaultPort (Integer defaultPort)
Sets the default server port.
Parameters
defaultPort the default port
Returns
the server
Referenced by com.globo.galeb.verticles.RouterVerticle.start().
static void com.globo.galeb.core.Server.setHttpServerName (String httpServerName) static
Sets the http server name.
Parameters
httpServerName the new http server name
Referenced by com.globo.galeb.handlers.rest.GetMatcherHandler.handle().
Server com.globo.galeb.core.Server.setHttpServerRequestHandler (final Handler< HttpServerRequest > httpServerRequestHandler)
Sets the http server request handler.
Parameters
httpServerRequestHandler the http server request handler
Returns
the server
Referenced by com.globo.galeb.verticles.RouterVerticle.start().
Server com.globo.galeb.core.Server.setWebsocketServerRequestHandler (final Handler< ServerWebSocket > websocketServerRequestHandler)
Sets the websocket server request handler.
Parameters
websocketServerRequestHandler the websocket server request handler
Returns
the server
Referenced by com.globo.galeb.verticles.RouterVerticle.start().
Server com.globo.galeb.core.Server.start (final Object caller)
Start server (call listen).
Parameters
caller the caller
Returns
the server
Referenced by com.globo.galeb.verticles.RouterVerticle.start().
The documentation for this class was generated from the following file:
src/main/java/com/globo/galeb/core/Server.java