Galeb: com.globo.galeb.metrics.StatsdClient.TypeStatsdMessage Enum Reference
com.globo.galeb.metrics.StatsdClient.TypeStatsdMessage Enum Reference
Public Member Functions
String getPattern ()
Public Attributes
COUNT =(PATTERN_COUNT)
TIME =(PATTERN_TIME)
GAUGE =(PATTERN_GAUGE)
SET =(PATTERN_SET)
Detailed Description
Enum TypeStatsdMessage.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Member Function Documentation
String com.globo.galeb.metrics.StatsdClient.TypeStatsdMessage.getPattern ()
Gets the pattern.
Returns
the pattern
Referenced by com.globo.galeb.metrics.StatsdClient.send().
Member Data Documentation
com.globo.galeb.metrics.StatsdClient.TypeStatsdMessage.COUNT =(PATTERN_COUNT)
The type count.
Referenced by com.globo.galeb.metrics.CounterWithStatsd.decrHttpCode(), com.globo.galeb.metrics.CounterWithStatsd.incrHttpCode(), com.globo.galeb.metrics.CounterWithStatsd.sendActiveSessions(), and com.globo.galeb.verticles.StatsdVerticle.start().
com.globo.galeb.metrics.StatsdClient.TypeStatsdMessage.GAUGE =(PATTERN_GAUGE)
The type gauge.
Referenced by com.globo.galeb.verticles.StatsdVerticle.start().
com.globo.galeb.metrics.StatsdClient.TypeStatsdMessage.SET =(PATTERN_SET)
The type set.
Referenced by com.globo.galeb.verticles.StatsdVerticle.start().
com.globo.galeb.metrics.StatsdClient.TypeStatsdMessage.TIME =(PATTERN_TIME)
The type time.
Referenced by com.globo.galeb.metrics.CounterWithStatsd.httpCode(), com.globo.galeb.metrics.CounterWithStatsd.requestTime(), and com.globo.galeb.verticles.StatsdVerticle.start().
The documentation for this enum was generated from the following file:
src/main/java/com/globo/galeb/metrics/StatsdClient.java