Galeb: com.globo.galeb.loadbalance.ILoadBalancePolicy Interface Reference
com.globo.galeb.loadbalance.ILoadBalancePolicy Interface Reference
Public Member Functions
Backend getChoice (final List< Backend > backends, final RequestData requestData)
boolean isDefault ()
String toString ()
Static Public Attributes
static final String CACHE_TIMEOUT_FIELDNAME = "cacheTimeout"
Detailed Description
Interface ILoadBalancePolicy.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Member Function Documentation
Backend com.globo.galeb.loadbalance.ILoadBalancePolicy.getChoice (final List< Backend > backends, final RequestData requestData)
Gets the choice.
Parameters
backends backends collection
requestData the request data
Returns
the backend chosen
Implemented in com.globo.galeb.loadbalance.impl.HashPolicy, com.globo.galeb.loadbalance.impl.LeastConnPolicy, com.globo.galeb.loadbalance.impl.RoundRobinPolicy, and com.globo.galeb.loadbalance.impl.RandomPolicy.
Referenced by com.globo.galeb.core.Virtualhost.getChoice().
boolean com.globo.galeb.loadbalance.ILoadBalancePolicy.isDefault ()
Checks if is default.
Returns
true, if is default
Implemented in com.globo.galeb.loadbalance.impl.HashPolicy, com.globo.galeb.loadbalance.impl.LeastConnPolicy, com.globo.galeb.loadbalance.impl.RandomPolicy, com.globo.galeb.loadbalance.impl.RoundRobinPolicy, and com.globo.galeb.loadbalance.impl.DefaultLoadBalancePolicy.
Referenced by com.globo.galeb.core.Virtualhost.getLoadBalancePolicy().
String com.globo.galeb.loadbalance.ILoadBalancePolicy.toString ()
Loadbalance string name
Returns
the loadbalance string name
Implemented in com.globo.galeb.loadbalance.impl.HashPolicy, com.globo.galeb.loadbalance.impl.LeastConnPolicy, com.globo.galeb.loadbalance.impl.RandomPolicy, com.globo.galeb.loadbalance.impl.RoundRobinPolicy, and com.globo.galeb.loadbalance.impl.DefaultLoadBalancePolicy.
Referenced by com.globo.galeb.core.Virtualhost.getLoadBalancePolicy().
Member Data Documentation
final String com.globo.galeb.loadbalance.ILoadBalancePolicy.CACHE_TIMEOUT_FIELDNAME = "cacheTimeout" static
The Constant CACHE_TIMEOUT_FIELDNAME.
Referenced by com.globo.galeb.loadbalance.impl.LeastConnPolicy.getChoice().
The documentation for this interface was generated from the following file:
src/main/java/com/globo/galeb/loadbalance/ILoadBalancePolicy.java