Galeb: com.globo.galeb.scheduler.IScheduler Interface Reference
com.globo.galeb.scheduler.IScheduler Interface Reference
Public Member Functions
IScheduler start ()
IScheduler setHandler (ISchedulerHandler schedulerHandler)
IScheduler setPeriod (Long period)
IScheduler cancel ()
IScheduler cancelHandler (Handler< Void > cancelHandler)
IScheduler cancelFailedHandler (Handler< Void > cancelFailedHandler)
Detailed Description
Interface IScheduler.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 22, 2014.
Member Function Documentation
IScheduler com.globo.galeb.scheduler.IScheduler.cancel ()
Cancel the scheduler.
Returns
IScheduler
Implemented in com.globo.galeb.scheduler.impl.VertxDelayScheduler, com.globo.galeb.scheduler.impl.VertxPeriodicScheduler, and com.globo.galeb.scheduler.impl.NullScheduler.
Referenced by com.globo.galeb.core.BackendSession.close(), com.globo.galeb.core.BackendSession.finalize(), com.globo.galeb.handlers.RouterRequestHandler.finalize(), com.globo.galeb.handlers.RouterResponseHandler.handle(), and com.globo.galeb.handlers.RouterRequestHandler.handle().
IScheduler com.globo.galeb.scheduler.IScheduler.cancelFailedHandler (Handler< Void > cancelFailedHandler)
Cancel failed handler.
Parameters
cancelFailedHandler the cancel failed handler
Returns
this
Implemented in com.globo.galeb.scheduler.impl.VertxDelayScheduler, com.globo.galeb.scheduler.impl.VertxPeriodicScheduler, and com.globo.galeb.scheduler.impl.NullScheduler.
IScheduler com.globo.galeb.scheduler.IScheduler.cancelHandler (Handler< Void > cancelHandler)
Cancel handler.
Parameters
cancelHandler the cancel handler
Returns
this
Implemented in com.globo.galeb.scheduler.impl.VertxDelayScheduler, com.globo.galeb.scheduler.impl.VertxPeriodicScheduler, and com.globo.galeb.scheduler.impl.NullScheduler.
Referenced by com.globo.galeb.handlers.RouterRequestHandler.handle().
IScheduler com.globo.galeb.scheduler.IScheduler.setHandler (ISchedulerHandler schedulerHandler)
Sets the handler.
Parameters
schedulerHandler the scheduler handler
Returns
IScheduler
Implemented in com.globo.galeb.scheduler.impl.VertxDelayScheduler, com.globo.galeb.scheduler.impl.VertxPeriodicScheduler, and com.globo.galeb.scheduler.impl.NullScheduler.
Referenced by com.globo.galeb.core.Backend.connect(), com.globo.galeb.handlers.RouterRequestHandler.handle(), and com.globo.galeb.verticles.HealthManagerVerticle.start().
IScheduler com.globo.galeb.scheduler.IScheduler.setPeriod (Long period)
Sets the scheduler period (ms).
Parameters
period the period
Returns
IScheduler
Implemented in com.globo.galeb.scheduler.impl.VertxDelayScheduler, com.globo.galeb.scheduler.impl.VertxPeriodicScheduler, and com.globo.galeb.scheduler.impl.NullScheduler.
Referenced by com.globo.galeb.core.BackendSession.connect().
IScheduler com.globo.galeb.scheduler.IScheduler.start ()
Start scheduler.
Returns
IScheduler
Implemented in com.globo.galeb.scheduler.impl.VertxDelayScheduler, com.globo.galeb.scheduler.impl.VertxPeriodicScheduler, and com.globo.galeb.scheduler.impl.NullScheduler.
Referenced by com.globo.galeb.core.BackendSession.connect(), com.globo.galeb.core.Backend.connect(), and com.globo.galeb.verticles.HealthManagerVerticle.start().
The documentation for this interface was generated from the following file:
src/main/java/com/globo/galeb/scheduler/IScheduler.java