Galeb: com.globo.galeb.metrics.ICounter Interface Reference
com.globo.galeb.metrics.ICounter Interface Reference
Public Member Functions
abstract void httpCode (String key, Integer code)
abstract void httpCode (String virtualhostId, String backendId, Integer code)
abstract void incrHttpCode (String key, Integer code)
abstract void incrHttpCode (String key, Integer code, double sample)
abstract void decrHttpCode (String key, Integer code)
abstract void decrHttpCode (String key, Integer code, double sample)
abstract void requestTime (String key, Long initialRequestTime)
abstract void requestTime (String virtualhostId, String backendId, Long initialRequestTime)
abstract void sendActiveSessions (String key, Long initialRequestTime)
abstract void sendActiveSessions (String virtualhostId, String backendId, Long initialRequestTime)
Detailed Description
Interface ICounter.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Member Function Documentation
abstract void com.globo.galeb.metrics.ICounter.decrHttpCode (String key, Integer code) abstract
Decrement http code count.
Parameters
key the key
code the code
Implemented in com.globo.galeb.metrics.CounterWithStatsd, com.globo.galeb.metrics.CounterWithEventBus, and com.globo.galeb.metrics.CounterConsoleOut.
abstract void com.globo.galeb.metrics.ICounter.decrHttpCode (String key, Integer code, double sample) abstract
Decrement http code count.
Parameters
key the key
code the code
sample the sample
Implemented in com.globo.galeb.metrics.CounterWithStatsd, com.globo.galeb.metrics.CounterWithEventBus, and com.globo.galeb.metrics.CounterConsoleOut.
abstract void com.globo.galeb.metrics.ICounter.httpCode (String key, Integer code) abstract
http code count.
Parameters
key the key
code the code
Implemented in com.globo.galeb.metrics.CounterWithStatsd, com.globo.galeb.metrics.CounterWithEventBus, and com.globo.galeb.metrics.CounterConsoleOut.
Referenced by com.globo.galeb.core.ServerResponse.sendRequestCount().
abstract void com.globo.galeb.metrics.ICounter.httpCode (String virtualhostId, String backendId, Integer code) abstract
http code count.
Parameters
virtualhostId the virtualhost id
backendId the backend id
code the code
Implemented in com.globo.galeb.metrics.CounterWithStatsd, com.globo.galeb.metrics.CounterWithEventBus, and com.globo.galeb.metrics.CounterConsoleOut.
abstract void com.globo.galeb.metrics.ICounter.incrHttpCode (String key, Integer code) abstract
Increment http code count.
Parameters
key the key
code the code
Implemented in com.globo.galeb.metrics.CounterWithStatsd, com.globo.galeb.metrics.CounterWithEventBus, and com.globo.galeb.metrics.CounterConsoleOut.
abstract void com.globo.galeb.metrics.ICounter.incrHttpCode (String key, Integer code, double sample) abstract
Increment http code count.
Parameters
key the key
code the code
sample the sample
Implemented in com.globo.galeb.metrics.CounterWithStatsd, com.globo.galeb.metrics.CounterWithEventBus, and com.globo.galeb.metrics.CounterConsoleOut.
abstract void com.globo.galeb.metrics.ICounter.requestTime (String key, Long initialRequestTime) abstract
Request time count.
Parameters
key the key
initialRequestTime the initial request time
Implemented in com.globo.galeb.metrics.CounterConsoleOut.
Referenced by com.globo.galeb.handlers.RouterResponseHandler.handle().
abstract void com.globo.galeb.metrics.ICounter.requestTime (String virtualhostId, String backendId, Long initialRequestTime) abstract
Request time count.
Parameters
virtualhostId the virtualhost id
backendId the backend id
initialRequestTime the initial request time
Implemented in com.globo.galeb.metrics.CounterWithStatsd, com.globo.galeb.metrics.CounterWithEventBus, and com.globo.galeb.metrics.CounterConsoleOut.
abstract void com.globo.galeb.metrics.ICounter.sendActiveSessions (String key, Long initialRequestTime) abstract
Send active sessions.
Parameters
key the key
initialRequestTime the initial request time
Implemented in com.globo.galeb.metrics.CounterWithStatsd, com.globo.galeb.metrics.CounterWithEventBus, and com.globo.galeb.metrics.CounterConsoleOut.
Referenced by com.globo.galeb.core.Backend.connect().
abstract void com.globo.galeb.metrics.ICounter.sendActiveSessions (String virtualhostId, String backendId, Long initialRequestTime) abstract
Send active sessions.
Parameters
virtualhostId the virtualhost id
backendId the backend id
initialRequestTime the initial request time
Implemented in com.globo.galeb.metrics.CounterWithStatsd, com.globo.galeb.metrics.CounterWithEventBus, and com.globo.galeb.metrics.CounterConsoleOut.
The documentation for this interface was generated from the following file:
src/main/java/com/globo/galeb/metrics/ICounter.java