Galeb: com.globo.galeb.core.bus.IQueueService Interface Reference
com.globo.galeb.core.bus.IQueueService Interface Reference
Classes
enum ACTION
Public Member Functions
void queueToAdd (JsonObject json, String uri)
void queueToDel (JsonObject json, String uri)
void queueToChange (JsonObject json, String uri)
void registerHealthcheck (ICallbackHealthcheck callbackHealthcheck)
void publishBackendOk (String backend)
void publishBackendFail (String backend)
void publishBackendConnections (String queueActiveConnections, JsonObject myConnections)
void registerConnectionsCounter (ICallbackConnectionCounter connectionsCounter, String queueActiveConnections)
void publishActiveConnections (String queueActiveConnections, JsonObject myConnections)
void unregisterConnectionsCounter (ICallbackConnectionCounter connectionsCounter, String queueActiveConnections)
void registerQueueAdd (Object starter, ICallbackQueueAction callbackQueueAction)
void registerQueueDel (Object starter, ICallbackQueueAction callbackQueueAction)
void registerQueueVersion (Object starter, ICallbackQueueAction callbackQueueAction)
void registerUpdateSharedData (Object starter, ICallbackSharedData callbackSharedData)
void updateSharedData ()
Static Public Attributes
static final String QUEUE_HEALTHCHECK_OK = "healthcheck.ok"
static final String QUEUE_HEALTHCHECK_FAIL = "healthcheck.fail"
static final String QUEUE_BACKEND_CONNECTIONS_PREFIX = "conn_"
Detailed Description
Interface IQueueService.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Member Function Documentation
void com.globo.galeb.core.bus.IQueueService.publishActiveConnections (String queueActiveConnections, JsonObject myConnections)
Publish active connections.
Parameters
queueActiveConnections the queue active connections
myConnections the local connections
Implemented in com.globo.galeb.core.bus.VertxQueueService.
Referenced by com.globo.galeb.core.Backend.publishConnection().
void com.globo.galeb.core.bus.IQueueService.publishBackendConnections (String queueActiveConnections, JsonObject myConnections)
Publish backend connections.
Parameters
queueActiveConnections the queue active connections
myConnections the local connections
Implemented in com.globo.galeb.core.bus.VertxQueueService.
void com.globo.galeb.core.bus.IQueueService.publishBackendFail (String backend)
Publish backendFail.
Parameters
backend the backend
Implemented in com.globo.galeb.core.bus.VertxQueueService.
Referenced by com.globo.galeb.core.BackendSession.connect(), and com.globo.galeb.handlers.RouterResponseHandler.handle().
void com.globo.galeb.core.bus.IQueueService.publishBackendOk (String backend)
Publish backendOk.
Parameters
backend the backend
Implemented in com.globo.galeb.core.bus.VertxQueueService.
void com.globo.galeb.core.bus.IQueueService.queueToAdd (JsonObject json, String uri)
Queue to add.
Parameters
json the json
uri the uri
Referenced by com.globo.galeb.handlers.rest.PostMatcherHandler.handle(), and com.globo.galeb.verticles.HealthManagerVerticle.moveBackend().
void com.globo.galeb.core.bus.IQueueService.queueToChange (JsonObject json, String uri)
Queue to change.
Parameters
json the json
uri the uri
Referenced by com.globo.galeb.handlers.rest.PutMatcherHandler.handle().
void com.globo.galeb.core.bus.IQueueService.queueToDel (JsonObject json, String uri)
Queue to del.
Parameters
json the json
uri the uri
Referenced by com.globo.galeb.handlers.rest.DeleteMatcherHandler.handle(), and com.globo.galeb.verticles.HealthManagerVerticle.moveBackend().
void com.globo.galeb.core.bus.IQueueService.registerConnectionsCounter (ICallbackConnectionCounter connectionsCounter, String queueActiveConnections)
Register connections counter.
Parameters
connectionsCounter the connections counter
queueActiveConnections the queue active connections
Referenced by com.globo.galeb.core.Backend.registerConnectionsCounter().
void com.globo.galeb.core.bus.IQueueService.registerHealthcheck (ICallbackHealthcheck callbackHealthcheck)
Register healthcheck.
Parameters
callbackHealthcheck the callback healthcheck
Referenced by com.globo.galeb.verticles.HealthManagerVerticle.start().
void com.globo.galeb.core.bus.IQueueService.registerQueueAdd (Object starter, ICallbackQueueAction callbackQueueAction)
Register queue to add.
Parameters
starter the starter
callbackQueueAction the callback queue action
Referenced by com.globo.galeb.core.Farm.registerQueueAction().
void com.globo.galeb.core.bus.IQueueService.registerQueueDel (Object starter, ICallbackQueueAction callbackQueueAction)
Register queue to del.
Parameters
starter the starter
callbackQueueAction the callback queue action
Referenced by com.globo.galeb.core.Farm.registerQueueAction().
void com.globo.galeb.core.bus.IQueueService.registerQueueVersion (Object starter, ICallbackQueueAction callbackQueueAction)
Register queue to version.
Parameters
starter the starter
callbackQueueAction the callback queue action
Referenced by com.globo.galeb.core.Farm.registerQueueAction().
void com.globo.galeb.core.bus.IQueueService.registerUpdateSharedData (Object starter, ICallbackSharedData callbackSharedData)
Register update shared data.
Parameters
starter the starter
callbackSharedData the callback shared data
Referenced by com.globo.galeb.core.Farm.registerQueueAction().
void com.globo.galeb.core.bus.IQueueService.unregisterConnectionsCounter (ICallbackConnectionCounter connectionsCounter, String queueActiveConnections)
Unregister connections counter.
Parameters
connectionsCounter the connections counter
queueActiveConnections the queue active connections
Referenced by com.globo.galeb.core.Backend.unregisterConnectionsCounter().
void com.globo.galeb.core.bus.IQueueService.updateSharedData ()
Update shared data.
Implemented in com.globo.galeb.core.bus.VertxQueueService.
Referenced by com.globo.galeb.core.Farm.getBackendJson(), com.globo.galeb.core.Farm.getFarmJson(), and com.globo.galeb.core.Farm.getVirtualhostJson().
Member Data Documentation
final String com.globo.galeb.core.bus.IQueueService.QUEUE_BACKEND_CONNECTIONS_PREFIX = "conn_" static
The Constant QUEUE_BACKEND_CONNECTIONS_PREFIX.
Referenced by com.globo.galeb.core.Backend.Backend().
final String com.globo.galeb.core.bus.IQueueService.QUEUE_HEALTHCHECK_FAIL = "healthcheck.fail" static
The Constant QUEUE_HEALTHCHECK_FAIL.
Referenced by com.globo.galeb.handlers.ws.BackendWebSocketHandler.handle(), and com.globo.galeb.core.bus.VertxQueueService.publishBackendFail().
final String com.globo.galeb.core.bus.IQueueService.QUEUE_HEALTHCHECK_OK = "healthcheck.ok" static
The Constant QUEUE_HEALTHCHECK_OK.
Referenced by com.globo.galeb.core.bus.VertxQueueService.publishBackendOk(), and com.globo.galeb.core.bus.VertxQueueService.registerHealthcheck().
The documentation for this interface was generated from the following file:
src/main/java/com/globo/galeb/core/bus/IQueueService.java