Galeb: com.globo.galeb.core.bus.ICallbackConnectionCounter Interface Reference
com.globo.galeb.core.bus.ICallbackConnectionCounter Interface Reference
Public Member Functions
void callbackGlobalConnectionsInfo (JsonObject body)
void setRegistered (boolean registered)
boolean isRegistered ()
Detailed Description
Interface ICallbackConnectionCounter.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Member Function Documentation
void com.globo.galeb.core.bus.ICallbackConnectionCounter.callbackGlobalConnectionsInfo (JsonObject body)
Callback global connections info.
Parameters
body the body
Implemented in com.globo.galeb.core.Backend.
boolean com.globo.galeb.core.bus.ICallbackConnectionCounter.isRegistered ()
Checks if is registered.
Returns
true, if is registered
Implemented in com.globo.galeb.core.Backend.
Referenced by com.globo.galeb.core.bus.VertxQueueService.registerConnectionsCounter(), and com.globo.galeb.core.bus.VertxQueueService.unregisterConnectionsCounter().
void com.globo.galeb.core.bus.ICallbackConnectionCounter.setRegistered (boolean registered)
Sets the registered.
Parameters
registered the new registered
Implemented in com.globo.galeb.core.Backend.
Referenced by com.globo.galeb.core.bus.VertxQueueService.registerConnectionsCounter(), and com.globo.galeb.core.bus.VertxQueueService.unregisterConnectionsCounter().
The documentation for this interface was generated from the following file:
src/main/java/com/globo/galeb/core/bus/ICallbackConnectionCounter.java