Galeb: com.globo.galeb.core.bus.ICallbackQueueAction Interface Reference
com.globo.galeb.core.bus.ICallbackQueueAction Interface Reference
Public Member Functions
void setVersion (long version)
boolean delFromMap (String body)
boolean addToMap (String body)
Detailed Description
Interface ICallbackQueueAction.
Author
: See AUTHORS file.
Version
: 1.0.0, Oct 23, 2014.
Member Function Documentation
boolean com.globo.galeb.core.bus.ICallbackQueueAction.addToMap (String body)
Adds to map.
Parameters
body the body
Returns
true, if successful
Implemented in com.globo.galeb.core.Farm.
Referenced by com.globo.galeb.core.bus.VertxQueueService.registerQueueAdd().
boolean com.globo.galeb.core.bus.ICallbackQueueAction.delFromMap (String body)
Del from map.
Parameters
body the body
Returns
true, if successful
Implemented in com.globo.galeb.core.Farm.
Referenced by com.globo.galeb.core.bus.VertxQueueService.registerQueueDel().
void com.globo.galeb.core.bus.ICallbackQueueAction.setVersion (long version)
Sets the version.
Parameters
version the version
Implemented in com.globo.galeb.core.Farm.
Referenced by com.globo.galeb.core.bus.VertxQueueService.registerQueueVersion().
The documentation for this interface was generated from the following file:
src/main/java/com/globo/galeb/core/bus/ICallbackQueueAction.java